ansible-collections/ibm_zos_core

README.md
docs/README-ZOAU.md
galaxy.yml

Update reference material with the latest git tag v0.0.4.
All version increments require that linked sources be updated to resolve. 

Update content to reflect latest version

---

README.md
docs/README-ZOAU.md
galaxy.yml
plugins/module_utils/job.py
plugins/modules/zos_job_output.py
plugins/modules/zos_job_submit.py
tests/functional/modules/test_zos_data_set_func.py
tests/functional/modules/test_zos_job_output_func.py
tests/functional/modules/test_zos_job_query_func.py
tests/functional/modules/test_zos_job_submit_func.py
tests/units/modules/test_zos_data_set_unit.py
tests/units/modules/test_zos_job_output_unit.py
tests/units/modules/test_zos_job_query_unit.py
tests/units/modules/test_zos_job_submit_unit.py

This merge will synchronized the latest master branch version 0.0.4 with the development branch. 

Update and merge master versions  to dev branch

---

README.md
README.rst
docs/Makefile
docs/source/community_guides.rst
docs/source/conf.py
docs/source/index.rst
docs/source/installation.rst
docs/source/modules.rst
docs/source/playbooks.rst
docs/source/plugins.rst
docs/source/quickstart.rst
docs/source/release_notes.rst
docs/source/requirements.rst
docs/templates/module.rst.j2
plugins/modules/zos_job_output.py
plugins/modules/zos_job_query.py

* This commit contains all the restructured text to build our webdocs
* This commit contains the make file needed to build the webdocs
* make clean.   - clean the generated source and dirs
* make ibm_zos_core. - generate rst for modules
* make html - generate the html based on all the rst
* make view - open browser and view index.html
* This commit contains the need jijna template to format ansible-doc
Building the webdoc have a number of required dependencies that will later be documented

Webdocs content for IBM z/OS Core Collection

---

docs/source/community_guides.rst
docs/source/conf.py
docs/source/index.rst
docs/source/installation.rst
docs/source/playbooks.rst
docs/source/plugins.rst
docs/source/quickstart.rst
docs/source/requirements.rst
docs/templates/module.rst.j2
galaxy.yml
plugins/modules/zos_data_set.py
plugins/modules/zos_job_output.py
plugins/modules/zos_job_query.py
plugins/modules/zos_job_submit.py

Integrated the teams review comments.

Integraded document review comments

---

tests/conftest.py

Fixes #132 ,  message artifacts left behind from merge 
```paste below
```

removed merge messages

---

docs/templates/module.rst.j2

Fixes Jinja template that would prior not align correctly with peer attributes. 

Bug in jinja where sample would not align correctly

---

README.rst
docs/source/index.rst
docs/source/playbooks.rst
docs/source/requirements.rst
galaxy.yml

Prepare galaxy configuration for the 1.0.0 release and update the web page link.
Update documentation with added information and URL corrections.

Updates to documentation and galaxy configuration

---

README.rst

Readme fix to a duplicate where "action plugins listed twice".

Fix to README.rst duplicate wording

---

docs/source/index.rst

Duplicate link for action plugins on index.rst page

Remove duplicate action plugins link

---

plugins/modules/zos_operator.py
tests/functional/modules/test_zos_operator_func.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt
tests/unit/test_zos_operator_unit.py

Initial commit for the zos_operator module.
zos_operator module

Initial commit for module zos_operator

---

playbooks/group_vars/all.yml

Fixes #970 in Jira, updates example PATH to use valid format and adding in /bin.
```paste below
```

fixed PATH

---

plugins/module_utils/data_set_utils.py

data_set_utils should be able to check whether a partitioned data set contains a specific member
data_set_utils

Check for data set member existence

---

plugins/modules/zos_encode.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

SUMMARY
Initial commit for moudle zos_encode (after merges)
ISSUE TYPE
Feature Pull Request
COMPONENT NAME
zos_encode

Merged branch and commit for zos_encode

---

plugins/modules/zos_encode.py
plugins/modules/zos_fetch.py

This is a quick update to add the fixed ZOAU import error message support to modules which were pulled to dev branch yesterday.
- Update Pull Request
- plugins/modules/zos_fetch.py
- plugins/modules/zos_encode.py

enhanced zoau import error message

---

playbooks/zos-collection-sample-v2.yaml
plugins/filter/wtor.py

Added a new sample playbook that leverages the latest modules in the collection/dev branch. Playbook focuses more on round trips and evaluating module responses and taking action, also included is a filter that is use by the sample playbook and serves as a good example. 

Added new playbook for latest module collection and a filter

---

plugins/modules/zos_fetch.py

Use the encode utility to convert encoding for remote files and data sets.
zos_fetch

Use encode util to convert encoding

---

plugins/modules/zos_fetch.py

Bugfix, update import name as a result of refactoring encode_utils to encode.

Fix import name change resulting from refactor

---

plugins/modules/zos_encode.py

Updates to the encode module documentation. 

Documentation updates, corrections and alterations

---

plugins/module_utils/copy.py

Copy util should be able to copy in binary mode.
copy

Add binary support for copying across USS and MVS

---

docs/source/installation.rst
docs/source/quickstart.rst
docs/source/requirements.rst

Minor updates in install,quickstart, and req pages

---

docs/Makefile

Make file update that cleans up the make file, reduces verbosity and provides an updated `make clean` that corrects directory structure on failure. 

Updated make file with comments and recover from failure

---

plugins/module_utils/backup.py
plugins/module_utils/encode.py
plugins/modules/zos_encode.py
tests/functional/modules/test_zos_encode_func.py

Update `mvs_file_backup` for non-SMS managed data sets.
backup

Update Backup util (mvs_file_backup)

---

plugins/modules/zos_job_submit.py

Fixes bug in zos_job_submit caused by Jobs.submit() incorrect output parsing.
- plugins/modules/zos_job_submit.py

removed Jobs.submit usage due to invalid response

---

galaxy.yml

Update to galaxy.yml to exclude additional files

Update to galaxy.yml to exclude files

---

plugins/module_utils/backup.py

Changes:
* Determine default back up path before validation
* Fix allocation command for `_allocate_model()`
backup

Bugfix MVS Backup

---

docs/Makefile
docs/source/conf.py

Update shpinx configuration options and add support for sphinx-versioning.

Shinx and sphinx-versioning support and updates

---

docs/source/installation.rst
plugins/modules/zos_encode.py
plugins/modules/zos_fetch.py
plugins/modules/zos_job_submit.py

Correct and update the documentation for installing a pre-release collection. 

Correct and update the installation of a pre-release

---

plugins/module_utils/data_set.py
plugins/modules/zos_encode.py
plugins/modules/zos_fetch.py

Changes:
+ Rename `data_set_utils -> data_set`
+ Use `MissingZOAUImport` for data_set util
+ Make data set utils function names more concise
+ Update `zos_fetch` and `zos_encode` to reflect the above changes
+ Data set util no longer requires the module to be passed to the constructor
data_set

Update data set utils

---

docs/zos-collection-index.rst

Initial commit for a new index file that will be used in the shared doc site. 

Added index file to support shared doc site

---

docs/source/playbooks.rst
playbooks/files/HELLO.jcl
playbooks/group_vars/all.yml
playbooks/zos-collection-sample-v2.yaml
playbooks/zos-collection-sample.yaml

Documentation edits made after a review. 

Doc review

---

plugins/action/zos_fetch.py
plugins/module_utils/better_arg_parser.py

This PR addresses issues that arise when using Python 2.6 on control node.

fix unsupported options python 2.6

---

plugins/action/zos_fetch.py
plugins/module_utils/better_arg_parser.py

Bugfix/python 2.6 support

---

plugins/module_utils/job.py
plugins/modules/zos_job_query.py

Add subsystem information to job query
Fixes #125
zos_job_query

Add system info to job query

---

docs/source/playbooks.rst
playbooks/group_vars/all.yml

Update configuration vars in doc and yml

---

plugins/module_utils/ansible_module.py
plugins/module_utils/backup.py
plugins/module_utils/copy.py
plugins/module_utils/data_set.py
plugins/module_utils/encode.py
plugins/module_utils/job.py
plugins/module_utils/vtoc.py
plugins/module_utils/zos_mvs_raw.py
plugins/modules/zos_copy.py
plugins/modules/zos_encode.py
plugins/modules/zos_mvs_raw.py
plugins/modules/zos_operator.py
tests/unit/test_zos_mvs_raw_unit.py

This PR addresses pending deprecation of check_invalid_arguments parameter on AnsibleModule.
The PR provides a wrapper class for AnsibleModule which will ignore the particular error raised when invalid arguments are found. I decided on a wrapper class as opposed to monkey patching AnsibleModule to simplify the process of using AnsibleModule and the patched version in the same module.

upload helper wrapper and fix usage

---

docs/source/conf.py

Fix  E231: missing whitespace

---

tests/conftest.py

This PR increases performance and cleanup of pipeline tests.
Improvements:
- Purging of job logs only occurs once at the end of test suite, instead of after every test, decreasing execution time.
- Purges all WTOR messages at the end of test suite, preventing issues we have seen in the past with WTOR buffer shortages causing test suite failures.
- Update Pull Request

improve cleanup

---

plugins/module_utils/job.py

This PR fixes #3544 in Jira. This fix accounts for various system configurations which may have defaults preventing jobs from being retrieved with our old command. This PR adds a secondary command which will run in the event the primary command fails to return any results. User who reported the problem confirmed this PR fixes the issue.
- plugins/module_utils/job.py

update job utility to handle various system configurations

---

docs/source/release_notes.rst
docs/source/requirements_managed.rst
docs/templates/breadcrumbs.html

Updates release notes and url's in our documentation.

release notes and url updates

---

tests/dependencyfinder.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

This PR addresses #4396 in Jira. This PR adds a new utility to the tests directory which can determine the test cases that need to run based off of the changes introduced by a pull request. 
- *tests/dependencyfinder.py* - The utility to find test dependencies

add dependency finder

---

docs/templates/module.rst.j2

This PR addresses all issues described in #222.
See the commit message for details.

Fixes #222: Fixed return value formatting issues in module template

---

README.md

This README update introduces consistency across all collections as part of the **Red Hat® Ansible Certified Content for IBM Z®**. 
README is used to represent the Galaxy, Hub and Github repositories landing page.

Update README to standardize across collections

---

docs/ansible_content.rst
docs/source/modules.rst

Update the module rst landing page to include module-doc and provide a better experience to users. 

Update module documentation to provide a better flow to the user

---

docs/scripts/role-sample-gen.sh
tests/functional/modules/test_zos_mvs_raw_func.py

This contains 2 issue fixes, one in a test, and one in a sample script.
No issue number - discovered during pipeline testing.
test_ zos_mvs_raw_function
also doc/scripts/role-samaple-gen.sh
The mvs_raw function had a few tests based on unusual assumptions.  They have been corrected.
The shell script didn't start with a 'shebang' triggering a strict error.
*** Pay attention to the auto-pipeline results... this led to an IPL and related issues on MP4, but should run cleanly.
```paste below
```

adding Blake's test change, and Rich's script change to a clean dev pull

---

plugins/modules/zos_blockinfile.py
plugins/modules/zos_lineinfile.py

return stderr if not empty

---

plugins/modules/zos_blockinfile.py

removed  quotes in the doc for 'block'

---

docs/ansible_content.rst

Doc update is to stream line our tie into the unified doc and to bring consistency with the other collections. 

Unfied doc consistency change for Ansible core content.

---

docs/source/modules/zos_copy.rst
docs/source/modules/zos_mvs_raw.rst
docs/source/release_notes.rst
meta/ibm_zos_core_meta.yml

Updates to release notes for version 1.3.0 to be promoted to Hub and Galaxy
Updates to modules docs to better represent behavior
Added new meta data about the collection for future use

Content/getting v.1.3.0 ready

---

tests/requirements.txt

Resolves the dated version of ansible-core 2.9 found in our tests/requirements.txt that is currently being flagged by depedabot scans. 
Resolves #331

Update dependency to use the latest with security patches

---

changelogs/fragments/334-words-matter.yml
docs/source/conf.py
docs/source/modules/zos_mvs_raw.rst
plugins/action/zos_fetch.py
plugins/modules/zos_copy.py
plugins/modules/zos_mvs_raw.py

This change works towards removing words in our offering that matter. Cleans up several references. 

Updates to correct use of words in our source

---

services/operations/SingletonCacheMeta.py
services/operations/cache.py
services/operations/connection.py
services/tests/test_cache.py

- prevent multiple instances of artifact cache, included test case in test_cache.py
```paste below
```

Singleton cache with test case

---

services/tests/connection_config.yaml
services/tests/test_cache.py
services/tests/test_connection.py
services/tests/test_operations.py

yaml config file added for connection args
config file

config file

---

services/tests/test_command.py

add unit tests for command services

command tests

---

services/operations/connection.py
services/tests/test_cache.py
services/tests/test_connection.py

This pull request updates the functional test cases with some added negative tests that are testing various use cases such as exceptions.
```paste below
```

Update functional tests with added use cases for the connection api

---

changelogs/fragments/501-allow-operator-set-command.yml
docs/source/release_notes.rst
plugins/modules/zos_operator.py
tests/dependencyfinder.py
tests/unit/test_zos_operator_unit.py

Correction to REXX code for operator call.  SET can pass to the slash command, QUERY cannot.
Fixes #353
Bugfix Pull Request
zos_operator

Bugfix zos_operator call in REXX code for SET keyword

---

changelogs/fragments/341-update-collection-tmphlq.yml
changelogs/fragments/393-tmphlq-dd-statements.yml

Corrected typo in change logs.
no component affected, just changelogs.
```paste below
```

Corrected typo in changelogs

---

plugins/modules/zos_data_set.py
plugins/modules/zos_mount.py

Both modules:
`zos_data_set`
`zos_mount`
had linting issues and with a minor code change I was able to resolve them, the details are actually in the issue #525 on how I resoled them. 
Resolves issue #525 
`zos_data_set`
`zos_mount`

Update modules to correct lint errors and unused import from AnsibleModule

---

docs/source/modules/zos_copy.rst
plugins/modules/zos_copy.py
tests/functional/modules/test_zos_copy_func.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.9.txt

Ports the bugfix for #496 from version 1.3.6 into 1.4.0-beta.2. 
zos_copy
The test cases added to zos_copy in 1.3.6 were parametrized and marked accordingly like the rest of the test cases for the module.

Ported bugfix for #496 from v1.3.6

---

plugins/modules/zos_mvs_raw.py

Added a hint of using the correct block style indicator when using multiline content inside dd_input.content value.
Fixes #373 
zos_mvs_raw
```paste below
```

Added block style indicator into zos_mvs_raw docs

---

.github/ISSUE_TEMPLATE/bug_issue.yml

Updates selection fields with latest zoau and z/OS Ansible core versions

Update git issue slection field

---

changelogs/fragments/727-zos-blockinfile-examples.yml
docs/source/modules/zos_blockinfile.rst
plugins/modules/zos_blockinfile.py

Addresses issue #430  that provides 2 examples that help users get started. These include using Jinja2 variables and files as block content.

Update zos_blockinfile with complex examples

---

changelogs/fragments/663-zos_gather_facts-update-docstring.yml
docs/source/modules/zos_gather_facts.rst
plugins/modules/zos_gather_facts.py

zos_gather_facts - add sample output to RETURN docstring

---

changelogs/fragments/725-zos_copy-encoding-bugs.yml
changelogs/fragments/743-zos_copy-encoding-bugs.yml
plugins/modules/zos_copy.py
tests/functional/modules/test_zos_copy_func.py

Port of the fixes for #664 and #678, taken from the changes committed to 1.5.0 (PR #725) 
zos_copy

Ported bugfixes for #664 and #678

---

CHANGELOG.rst
README.md
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
docs/source/release_notes.rst
galaxy.yml
meta/ibm_zos_core_meta.yml
meta/runtime.yml
plugins/module_utils/encode.py
plugins/module_utils/job.py
plugins/modules/zos_gather_facts.py
tests/dependencyfinder.py
tests/functional/modules/test_zos_job_submit_func.py

Merge main into dev to transfer the git tag and any chance some code which was in 1.5 was not added to 1.6 during branching to release

Merge main to dev

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
docs/source/modules/zos_blockinfile.rst
docs/source/modules/zos_data_set.rst
docs/source/modules/zos_job_query.rst
docs/source/modules/zos_lineinfile.rst
docs/source/modules/zos_tso_command.rst
docs/source/modules/zos_volume_init.rst
docs/source/release_notes.rst
galaxy.yml
meta/ibm_zos_core_meta.yml
plugins/action/zos_fetch.py
plugins/module_utils/system.py
plugins/modules/zos_volume_init.py
tests/functional/modules/test_zos_copy_func.py
tests/functional/modules/test_zos_data_set_func.py
tests/functional/modules/test_zos_find_func.py
tests/functional/modules/test_zos_job_query_func.py
tests/functional/modules/test_zos_lineinfile_func.py

Part of the release for 1.6.0-beta.1 is to merge all the updated meta data back to dev for releases to build onto. This is for issue #606

Merge master to dev for 1.6.0 beta.1

---

ac
changelogs/fragments/789-ac-command-add-test.yml

Addresses issue #792 that will add the ability to run a single test from a test suite.
This is now supported:
```
$ ac --ac-test --host ec01150a --python 3.10 --zoau 1.2.2 --file tests/functional/modules/test_zos_operator_func.py --test  test_zos_operator_positive_path --debug true
```
```
ac-test:          Run the functional tests inside the managed python virtual environment.
Supports format: <option> <value> and <option>=<value>
Usage: ac [--ac-test] [--host <host>] [--python <python>] [--zoau <zoau>] [--file <file>] [--debug <boolean>]
Options:
host     - z/OS managed node to run test cases, no selection defaults to
a host registerd to your user id (`whoami`).
python   - IBM enterprise python version, choices are 3.8, 3.9, 3.10, 3.11,
no selection defauls to 3.8.
zoau     - ZOAU to …
```

Update ac to support a single test

---

changelogs/fragments/783_fix_zoau_version_checker.yml

Forgot to include a changelog fragment for zoau version checker bugfix PR #797

add changelog fragment for zoau version checker bugfix

---

tests/functional/modules/test_zos_copy_func.py

Remove unnecessary line and change for functional.

Change the line for the functional one

---

.ansible-lint
ac
changelogs/fragments/812-ansible-lint.yml
galaxy.yml
meta/runtime.yml

This addresses issue #809 partially. There is still the remaining CI/CD work to be done that is not managed in this repository. We can continue to track the CI/CD work for ansible-lint using this git issue #809 but can consider this issue complete for now. 

Add ansible-lint tooling added

---

changelogs/fragments/816-zos_data_set-update-vsam.yml
docs/source/modules/zos_data_set.rst
plugins/module_utils/data_set.py
plugins/modules/zos_data_set.py
tests/functional/modules/test_zos_data_set_func.py
tests/sanity/ignore-2.16.txt

Same as PR #791 but for v1.6.0 (backport)
Given this change will drive over 700 tests it made sense to collapse all the related zos_data_set into one PR to avoid multiple regression pipelines.
1. Documentation: When a MEMBER is created, the format type of the member was not described, it should be clearly defined so that a user does not try to insert an executable into the data formatted member. Issue #631 
2. Bug: A random issue would occur on the pipeline leaving behind VSAM cluster components be it INDEX or DATA, originally this was thought to be a test case issue and a simple test fix but after reviewing I found it much more complex and took a better part of the week to address. To fix this I had to undo most of what was done in  PR …

Update zos_data_set member description created

---

changelogs/fragments/959-ac-tool-update-mounts.yml
scripts/mounts.env

Trivial, updated mounts.env with latest zoau versions, 1.2.4 and 1.2.5.
ac

Updated mounts.evn with latests zoau mounts

---

changelogs/fragments/916-zos-lineinfile-does-not-behave-community.yml
changelogs/fragments/918-zos-operator-response-come-back-truncate.yaml
changelogs/fragments/952-zos-job-submit-truncate-final-character.yml

Trivial change from bugfix tag to bugfixes in different changelog fragments.
changelogs
```paste below
```

Corrected changelog tag from bugfix to bugfixes

---

changelogs/fragments/966-ac-tool-add-python-311-3.yml
scripts/mounts.env

Trivial pull request, add python 3.11-3 into mounts.env.
No regression test is needed
ac tool

Add python 3.11-3 to ac mount tables

---

changelogs/fragments/1018-internal-consolidate-version-checks.yml
plugins/module_utils/job.py
plugins/module_utils/zoau_version_checker.py
tests/functional/modules/test_zos_job_submit_func.py

Consolidate the different version checks to use one routine
Fixes #1018
- zos_operator
- zos_operator_action_query
- utils/job.py and 
- utils/zoau_version_checker.py

main change to version checker for consolidation

---

changelogs/fragments/1029-validate-path-join.yml
changelogs/fragments/1034-document-utf8-known-issue.yml
changelogs/fragments/918-zos-operator-response-come-back-truncate.yaml
changelogs/fragments/934-Remove-conditional-unnecessary.yml
changelogs/fragments/943-enhance-Add-wait-zos-operator-and-query.yml
changelogs/fragments/951-Change-copy-for-zos-copy-and-remove-temporary-files.yml
changelogs/fragments/952-zos-job-submit-truncate-final-character.yml
changelogs/fragments/963-validate-path-join.yml
changelogs/fragments/965-enhance-archive-tests.yml

Adds known issues for UTF8 non-printable chars. See issue #1034 

Add known issues doc for utf8 issues

---

docs/source/release_notes.rst

Added a link and minor edits to release notes for 1.8.0-beta.1
- Docs Pull Requestt

update release notes

---

changelogs/fragments/1056-Update_sanity_ignore_2_16.yml
tests/sanity/ignore-2.16.txt

Removes sanity ignore for zos_copy 
Removes sanity ignore 2-16 for zos_copy about doc-default-does-not-match-spec and doc-type-does-not-match-spec

Update_sanity_ignore 2_16

---

plugins/module_utils/system.py

Removed unused imports from recently commented module_utils/system.py, this was breaking the sanity issues from 2.16.
No issue was created for this.
- Sanity issues Pull Request
module_utils/system.py

Removed unused imports from module_utils/system.py

---

changelogs/fragments/1065-rexx-exec-tso_command.yml
changelogs/fragments/1072-rexx-exec-tso_command.yml
docs/source/modules/zos_tso_command.rst
plugins/modules/zos_tso_command.py

Fixes #1021. Backport of #1065.

[v1.8.0] [backport] [Documentation] [zos_tso_command] Add REXX exec example

---

changelogs/fragments/1074-improve-job-submit-error-msgs.yml
plugins/action/zos_job_submit.py

Modify zos_job_submit error messages in action plugin to be clearer.
Fixes #1050 
zos_job_submit

[Enhancement][zos_job_submit] Modify error messages to be clearer

---

changelogs/fragments/1089-update-managed_node_doc.yml
docs/source/requirements-single.rst
docs/source/requirements_managed.rst

some links in our docsite seemed to be broken or outdated, this PR updates those links.
no unit/functional tests ran (nor should they have since it's a doc-only change), but syntax and other checks seem to be ok

update link in managed_node doc

---

scripts/mounts.env

Updates the list contained in `scripts/mounts.env` to include the share for ZOAU v.1.3.0.
`ac` script

Update ZOAU list to include v1.3.0

---

changelogs/fragments/1152-zos-lineinfile-remove-zos_copy-dependency.yml
tests/functional/modules/test_zos_lineinfile_func.py

Removed the zos_copy call from zos_lineinfile test cases.
Fixes #1135 
- Trivial Pull Request
zos_lineinfile test cases
```paste below
```

[v1.10.0][zos_lineinfile] Removed zos_copy dependency from test cases 

---

changelogs/fragments/1157-remove-zos-copy-from-zos-encode-tests.yml
tests/functional/modules/test_zos_encode_func.py

Removed zos_copy dependency from zos_encode test cases.
Fixes #1131 
zos_encode

[v1.10.0][zos_encode] Remove zos_copy dependency from test cases

---

changelogs/fragments/1167-remove-zos-copy-from-zos-blockinfile-tests.yml
tests/functional/modules/test_zos_blockinfile_func.py

Removes the use of zos_copy from zos_blockinfile test cases.
Fixes #1130 
zos_blockinfile

[v1.10.0][zos_blockinfile] Remove zos_copy from test cases

---

changelogs/fragments/1179-remove-zos_encode-from_zos_lineinfile-tests.yml
tests/functional/modules/test_zos_lineinfile_func.py

Remove zos_encode from zos_lineinfile.
Fixes #1134
zos_lineinfile

[v1.10.0][zos_lineinfile] Remove zos encode from zos lineinfile

---

changelogs/fragments/1176-copy-members.yml
changelogs/fragments/1183-copy-members.yml
plugins/modules/zos_copy.py
tests/functional/modules/test_zos_copy_func.py

[v1.10.0] [zos_copy] Enhance zos_copy performance when copying multiple PDS members 

---

changelogs/fragments/1169-migrate-module-utils-copy.yml
changelogs/fragments/1187-migrate-module-utils-copy.yml
plugins/module_utils/copy.py

Updated module_uils/copy.py.
Fixes #1117
zos_copy

[v1.10.0] [module_utils/copy.py] Implement ZOAU 1.3 migration changes into module_utils/copy.py

---

changelogs/fragments/1190-migrate-module_utils-dd_statement.yml
plugins/module_utils/dd_statement.py

Migrated module_utils/dd_statement to use ZOAU 1.3
Fixes #1119
module_utils/dd_statement.py

[v1.10.0] [module_utils/dd_statement.py] Implement ZOAU 1.3 migration changes into module_utils/dd_statement.py

---

changelogs/1188-migrate-module_utils-backup.yml
changelogs/fragments/1188-migrate-module_utils-backup.yml
plugins/module_utils/backup.py

Migrated module_utils/backup.py to use ZOAU 1.3 code.
Fixes #1115 
module_utils/backup.py

[v1.10.0] [module_utils/backup.py] Implement ZOAU 1.3 migration changes into module_utils/backup.py

---

changelogs/fragments/1182-migrate-module-utils-data-set.yml
plugins/module_utils/data_set.py

Implemented datasets module latest changes from ZOAU 1.3
Fixes #1118 
module_utils/data_set.py

[v1.10.0][module_utils/data_set.py] Implement ZOAU 1.3 migration changes into module_utils/data_set.py

---

changelogs/fragments/1218-migrate-zos_encode.yml
plugins/module_utils/data_set.py
plugins/modules/zos_encode.py
tests/functional/modules/test_zos_encode_func.py

Migrated zos_encode to use ZOAU 1.3 by updating the ZOAU import and correcting a bug in the module_utils.
Fixes #1107 
zos_encode

[v1.10.0][zos_encode] Migrate zos_encode to use ZOAU 1.3

---

changelogs/fragments/1229-migrate-zos_fetch.yml
plugins/modules/zos_fetch.py
tests/functional/modules/test_zos_fetch_func.py

Migrated the module to use the latest ZOAU 1.3 code.
Updated a test which used a now deprecated wait option.
Fixes #1108 
zos_fetch

[v1.10.0][zos_fetch] Migrate zos_fetch to ZOAU 1.3

---

changelogs/fragments/1237-migrate-zos_mount.yml
tests/functional/modules/test_zos_mount_func.py

Fixes #1127 and #1143.
- zos_mount

[v1.10.0] [zos_mount] zos_mount ZOAU v1.3.0 migration

---

changelogs/fragments/1238-migrate-zos_unarchive.yml

I just ran `antsibull-changelog lint` in dev branch and looks like a trailing char was introduced in one 
changelog

Changelog lint : Removed a trailing s character from fragment entry

---

changelogs/fragments/992-fix-sanity4to6.yml
plugins/module_utils/data_set.py
plugins/modules/zos_data_set.py
tests/functional/modules/test_zos_data_set_func.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.9.txt

SUMMARY
This ticket is for the forward-part of the zos_data_set module for the new 1.3.0 development work.
Changes will resolving sanity test linting issues #992, #993, #994
ISSUE TYPE
Bugfix Pull Request
COMPONENT NAME
zos_data_set

[v1.10.0] [Enabler] [zos_data_set] Enabler/992/fixsanityfourin110

---

changelogs/fragments/1348-update-docstring-zos_encode.yml
plugins/modules/zos_encode.py

Update docstrings on zos_encode to the numpy standard
zos_encode.py
```paste below
```

[Documentation][zos_encode] Add and standarize docstrings on modules/zos_encode.py

---

changelogs/fragments/1349-update-docstring-zos_fetch.yml
plugins/modules/zos_fetch.py

Update docstrings on zos_fetch to the numpy standard
zos_fetch.py
```paste below
```

[Documentation][zos_fetch] Add and standarize docstrings on modules/zos_fetch.py

---

changelogs/fragments/1353-update-docstring-zos_job_query.yml
plugins/modules/zos_job_query.py

Update docstrings on zos_job_query to the numpy standard
zos_job_query.py
```paste below
```

[Documentation][zos_job_query] Add docstrings to modules/zos_job_query.py

---

changelogs/fragments/1389-update-docstring-zos_script.yml
changelogs/fragments/1390-update-docstring-zos_script.yml
plugins/modules/zos_script.py

Update docstrings on zos_script to the numpy standard
zos_script.py
```paste below
```

[Documentation][zos_script] Add and standarize docstrings on modules/zos_script.py

---

changelogs/fragments/1323-Update_docstring-zos_operator_action_query.yml
changelogs/fragments/1394-Update_docstring-zos_operator_action_query.yml
plugins/modules/zos_operator_action_query.py

Update docstrings on zos_operator_action_query to the numpy standard
zos_operator_action_query.py
```paste below
```

[Documentation][zos_operator_action_query] Add and standarize docstrings on modules/zos_operator_action_query.py

---

changelogs/fragments/1350-update-docstring-zos_find.yml
plugins/modules/zos_find.py

Update docstrings on zos_find to the numpy standard
zos_find.py
```paste below
```

[Documentation][zos_find] Add and standarize docstrings on modules/zos_find.py

---

changelogs/fragments/1352-update-docstring-zos_job_output.yml
plugins/modules/zos_job_output.py

Update docstrings on zos_job_output to the numpy standard
Addresses part of #1316 
zos_job_output
```paste below
```

[Documentation][zos_job_output] Add and standarize docstrings on modules/zos_job_output.py

---

changelogs/fragments/1356-update-docstring-zos_mount.yml
plugins/modules/zos_mount.py

Update docstrings on zos_mount to the numpy standard
zos_mount.py
```paste below
```

[Documentation][zos_mount] Add and standarize docstrings on modules/zos_mount.py

---

changelogs/fragments/1336-update-docstring-validation.yml
plugins/module_utils/validation.py

Update docstrings on validation to the numpy standard
validation.py
```paste below
```

[Documentation][validation] Add docstrings to module_utils/validation.py

---

changelogs/fragments/1333-update-docstring-job.yml
plugins/module_utils/job.py

Update docstrings on job to the numpy standard
job.py
```paste below
```

[Documentation][job] Add docstrings to module_utils/job.py

---

changelogs/fragments/1331-update-docstring-ickdsf.yml
plugins/module_utils/ickdsf.py

Update docstrings on ickdsf to the numpy standard
ickdsf.py
```paste below
```

[Documentation][ickdsf] Add docstrings to module_utils/ickdsf.py

---

ac
changelogs/fragments/1484-update-ac-tool-ansible-lint.yml
scripts/mounts.env
scripts/mounts.sh
scripts/requirements-2.12.env
scripts/requirements-2.13.env
scripts/requirements-2.14.env
scripts/requirements-2.15.env
scripts/requirements-2.17.env
scripts/requirements-latest.env
scripts/venv.sh

Addresses #1325 and also expands beyond RSA support, includes ansible-core 2.17-beta support.
- Support for ansible-lint 6.22 was added to all managed venv's
- Support for additional algorithm support because some of the systems don't agree on RSA as a mutual signature algorithm.
- Added a venv template for ansible-core 2.17-beta
- Added the option to choose which venv to start based on its name (also added for stopping a venv)
- Added support to create a managed venv of the latest devel source in the community for ansible-core.
- fixed a script issues location awareness that resulting in error when run from another script, added a env for 2.17.
For example:` ./ac --venv-start --name venv-latest` results in `ansible-playbook [core 2.18.0.dev0]`
```
~/git/gh/ibm_zos_core $: ./ac …
```

Update ac tool to support ansible-lint 6.22 and expanded beyond RSA support. 

---

changelogs/fragments/1335-update-docstring-template.yml
plugins/module_utils/template.py

Update docstrings on template to the numpy standard
template.py
```paste below
```

[Documentation][template] Standarize docstrings in module_utils/template.py

---

changelogs/fragments/1337-update-docstring-vtoc.yml
plugins/module_utils/vtoc.py

Update docstrings on vtoc to the numpy standard
vtoc.py
```paste below
```

[Documentation][vtoc] Add docstrings to module_utils/vtoc.py

---

docs/source/release_notes.rst

Fixes support matrix url in release notes.

Fix url for support matrix

---

scripts/mounts.env

AC only switching zoau mounts to remove 1.0.0 gfa and add 1.3.2.0
Fixes AC
- Feature Pull Request - AC not customer facing.
AC/mounts.env

Zoau132mount

---

tests/functional/modules/test_zos_lineinfile_func.py

Fix lineinfile

---

README.md
changelogs/fragments/1552-readme-support-updates.yml
docs/source/release_notes.rst
docs/source/resources/releases_maintenance.rst

Update README , release notes and support matrix.
Issue #[1552](https://github.com/ansible-collections/ibm_zos_core/issues/1552)

Doc updates for README , release notes and support matrix.

---

changelogs/fragments/1635-backup_restore_portability.yml
tests/functional/modules/test_zos_backup_restore.py

Enabler backup restore portability
Fixes #1578 
- Enable Pull Request
Change additional names aleatory and hlq aleatory to the test suite.

[Enabler][1578]backup_restore_portability

---

changelogs/fragments/1654-zos_apf_tests_change_temphlq.yml
tests/functional/modules/test_zos_apf_func.py

[Enabler] [zos_apf] Change temporary HLQ used in tests

---

changelogs/fragments/1642-Ensure_portability_zos_encode.yml
tests/functional/modules/test_zos_encode_func.py

Remove hardcoded content of files and dataset names.
Fixes #1595 
Add date time for files names and delete hardcoded dataset names.

[Enabler][1595]Ensure_portability_zos_encode

---

changelogs/fragments/1658-job_submit_portability.yml
tests/functional/modules/test_zos_job_submit_func.py

Delete uss and dataset files
Fixes #1592 
zos_job_submit

[Enabler][1592]job_submit_portability

---

changelogs/fragments/1677-zos_job_query_portability.yaml
tests/functional/modules/test_zos_job_query_func.py

Remove hardcoded job_id
Fixes #1591 

[Enabler][1591]zos_job_query_portability

---

changelogs/fragments/1687-lineinfile_portability.yml
tests/functional/modules/test_zos_lineinfile_func.py

Portability lineinfile
Fixes #1686 

[Enabler][1686]lineinfile_portability

---

CHANGELOG.rst
README.md
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/fragments/v1.11.0-beta.1_summary.yml
changelogs/fragments/v1.11.0_summary.yml
docs/source/modules/zos_archive.rst
docs/source/modules/zos_blockinfile.rst
docs/source/modules/zos_encode.rst
docs/source/modules/zos_find.rst
docs/source/modules/zos_lineinfile.rst
docs/source/modules/zos_unarchive.rst
docs/source/release_notes.rst
docs/source/resources/releases_maintenance.rst
galaxy.yml
meta/ibm_zos_core_meta.yml
plugins/action/zos_job_submit.py
plugins/modules/zos_blockinfile.py
plugins/modules/zos_copy.py
plugins/modules/zos_lineinfile.py
plugins/modules/zos_mvs_raw.py
plugins/modules/zos_unarchive.py
tests/functional/modules/test_zos_copy_func.py
tests/functional/modules/test_zos_encode_func.py

Release activities for version 1.11.0 GA in issue #1621

Staging v1.11.0

---

changelogs/fragments/1756-update-docstrings-zos_unarchive.yml
plugins/modules/zos_unarchive.py

Back when Isaac updated our docstrings to use lumpy styling we stalled a couple of PRs because we had some changes pending. Now, the code had diverged way too much so I added the docstrings again in a clean branch.
This is the original PR #1413  by @IsaacVRey.
zos_unarchive 
```paste below
```

[Documentation][zos_unarchive]Updated the docstrings in zos_unarchive to comply with numpy styling

---

changelogs/fragments/1751-Avoid_parsing_on_job_utils.yml
plugins/module_utils/job.py

Remove parsing response and use value already obtain
Fixes #1722 

[enabler][1722]Avoid_parsing_on_job_utils

---

changelogs/fragments/1762-zos_mvs_raw-inconsistent-verbose.yml
plugins/module_utils/zos_mvs_raw.py
plugins/modules/zos_mvs_raw.py
tests/functional/modules/test_zos_mvs_raw_func.py

Fixes #1755 
zos_mvs_raw
```paste below
```

[1.9.3][zos_mvs_raw] Consistently fail if return code is not zero

---

ac
changelogs/fragments/1784-ac-added-flake8-collections-mapping.yml
scripts/venv.sh

Addresses issues #1782 and #1783.
Adds support for flake8 with proper config file. 
Adds support/fixes the collection mapping into a venv.

Add flake8 and bug fix venv in the AC tool.

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/v1.9.4_summary.yml
docs/source/release_notes.rst
galaxy.yml
meta/ibm_zos_core_meta.yml

Release tasks for v1.9.4
- Release Pull Request
```paste below
```

Staging v1.9.4 tasks

---

changelogs/fragments/1813-implement_max_rc_mvs_raw.yml
plugins/modules/zos_mvs_raw.py
tests/functional/modules/test_zos_mvs_raw_func.py

Add max_rc as parameter to mvs_raw module
Fixes #1447 
- Enancement Pull Request
Add conditionals to show error or proper work but with change as false

[enhancement][mvs_raw]Implement_max_rc_mvs_raw

---

changelogs/fragments/1842-Add_test_case_to_validate_advance_regular_expression.yml
tests/functional/modules/test_zos_lineinfile_func.py

Add test case to validate use of advance regular expression
Fixes #913 
Test case for validation of bug fix from ZOAU python API

[bugfix][lineinfile]Add_test_case_to_validate_advance_regular_expression

---

changelogs/fragments/1851-remove_hard_coded_python_path.yml
tests/functional/modules/test_zos_operator_func.py

Remove all hardcoded python path
Fixes #1850 

[bugfix][zos_operator]remove_hardcoded_python_path

---

changelogs/fragments/1900-zos_job_query-map_system_subsystem.yml
plugins/module_utils/job.py
tests/functional/modules/test_zos_job_query_func.py

Mapping system and subsystem values directly from zoau to zos_job_query response #1694 
zos_job_query
zos_job_query response
```
{
"changed": false,
"failed": false,
"jobs": [
{
"asid": 0,
"content_type": "JOB",
"creation_date": "2025-01-31",
"creation_time": "3:12:05",
"execution_time": "00:00:02",
"job_class": "R",
"job_id": "JOB00273",
"job_name": "SLEEP",
"owner": "USER",
"priority": 1,
"program_name": "BPXBATCH",
"queue_position": 28,
"ret_code": {
"code": 0,
"msg": "CC"
},
"subsystem": "JES2",
"svc_class": null,
"system": "ZOSSERVER"
}
],
"message": ""
}
}
```

[Enhancement][zos_job_query] Map system and subsystem from ZOAU reponse

---

changelogs/fragments/1932-zos_copy-asa-dest-lock-support.yml
plugins/module_utils/copy.py
plugins/modules/zos_copy.py
tests/functional/modules/test_zos_copy_func.py

Fixes #1909.
- module_utils/copy.py
- zos_copy

[Bugfix] [v1.12.1] [zos_copy] Add force_lock when copying into an ASA data set

---

changelogs/fragments/1936-wrong_behaviour_force_lock_parameter.yml
plugins/modules/zos_copy.py
tests/functional/modules/test_zos_copy_func.py

Por forward of solution.
Fixes #1898 

[Bugfix][1898][zos_copy][port_forward][1.13]wrong_behaviour_force_lock_parameter

---

changelogs/fragments/1938-add-large-type-zos_copy.yml
docs/source/modules/zos_copy.rst
plugins/modules/zos_copy.py

[Documentation] [zos_copy] Add large option in dest_data_set type

---

changelogs/fragments/1932-zos_copy-asa-dest-lock-support.yml
changelogs/fragments/1939-zos_copy_asa-dest-lock-support.yml
plugins/module_utils/copy.py
plugins/modules/zos_copy.py
tests/functional/modules/test_zos_copy_func.py

Fixes #1909. Port from the fix found in v1.12.1.
- module_utils/copy.py
- zos_copy

[Bugfix] [Forward port] [v1.13.0] [zos_copy] Use of force_lock with ASA data sets

---

.github/ISSUE_TEMPLATE/bug_issue.yml
.github/ISSUE_TEMPLATE/collaboration_issue.yml
.github/ISSUE_TEMPLATE/doc_issue.yml

Changes to support forms to include 1.13.0-beta.1 in the version lists
support forms in the github folder

Form for 1.13.0-b1

---

changelogs/fragments/1939-zos_copy_asa-dest-lock-support.yml
changelogs/fragments/1941-zos_copy-asa-dest-lock-support.yml
plugins/module_utils/copy.py
plugins/modules/zos_copy.py
tests/functional/modules/test_zos_copy_func.py

Fixes #1909. Porting the bugfix over to dev.
- module_utils/copy.py
- zos_copy

[Bugfix] [Forward port] [zos_copy] Use of force_lock with ASA data sets

---

changelogs/fragments/1934-zos_script-implemented-async-support
plugins/action/zos_script.py
plugins/modules/zos_script.py
tests/functional/modules/test_zos_script_func.py

Added async support for zos_script #1878 
zos_script
Implemented asynchronous support for zos_script and added synchronous support for zos_copy module internal call. Added test case also.
Jenkins job: https://billies1.fyre.ibm.com/job/ansible-zos-core-dev-1/458/

[Enhancement] [zos_script] Implement async support for zos_script

---

changelogs/fragments/2000-documentation-for-check_mode-all-modules.yml
plugins/modules/zos_apf.py
plugins/modules/zos_archive.py
plugins/modules/zos_backup_restore.py
plugins/modules/zos_blockinfile.py
plugins/modules/zos_copy.py
plugins/modules/zos_data_set.py
plugins/modules/zos_encode.py
plugins/modules/zos_fetch.py
plugins/modules/zos_find.py
plugins/modules/zos_gather_facts.py
plugins/modules/zos_job_output.py
plugins/modules/zos_job_query.py
plugins/modules/zos_job_submit.py
plugins/modules/zos_lineinfile.py
plugins/modules/zos_mount.py
plugins/modules/zos_mvs_raw.py
plugins/modules/zos_operator.py
plugins/modules/zos_operator_action_query.py
plugins/modules/zos_ping.py
plugins/modules/zos_script.py
plugins/modules/zos_tso_command.py
plugins/modules/zos_unarchive.py
plugins/modules/zos_volume_init.py
plugins/modules/zos_zfs_resize.py

Adding the documentation to all modules regarding check mode
| Module | check_mode supported | 
| --- | --- | 
| zos_apf – Add or remove libraries to Authorized Program Facility (APF) | No |
| zos_archive – Archive files and data sets on z/OS. | YES |
| zos_backup_restore – Backup and restore data sets and volumes | No |
| zos_blockinfile – Manage block of multi-line textual data on z/OS | No |
| zos_copy – Copy data to z/OS | No | 
| zos_data_set – Manage data sets | YES |
| zos_encode – Perform encoding operations. | No |
| zos_fetch – Fetch data from z/OS | No|
| zos_find – Find matching data sets | No |
| zos_gather_facts – Gather z/OS system facts.| YES |
| zos_job_output – Display job output | YES |
| zos_job_query – Query job status | YES |
| zos_job_submit – Submit JCL | YES |
| …

Adding the check mode documentation

---

ac
changelogs/fragments/2028-add-refresh-command-ac-tool.yml

Updated the ac tool to include a --refresh-env option, allowing users to refresh mount tables and scripts in existing environments without needing to remove and recreate the venv folder. The new commands are:
./ac --refresh-env to refresh the active environment.
./ac --refresh-env --all to refresh all environments.
./ac --refresh-env --name=venv-2.18 to refresh a specific environment."
Fixed #1948 
- AC Script 
```
- Command 1 : ./ac --refresh-env
- Ran Refresh Command for current env 
- MacBook-Pro ibm_zos_core % ./ac --refresh-env                          
-----------------------------------------------------------------------
INFO: Refreshing: venv-2.18
----------------------------------------------------------------------- …
```

[AC] Add new option to ac tool to refresh venv scripts

---

changelogs/fragments/2058-Add_sanity_ignore_for_2_18.yml
tests/sanity/ignore-2.18.txt

Add sanity ignore for Ansible 2.18.

[Documentation]Add_sanity_ignore_for_ansible_2_18

---

changelogs/fragments/2048-alias-support-zos_stat.yml
docs/source/modules/zos_stat.rst
plugins/module_utils/data_set.py
plugins/modules/zos_stat.py
tests/functional/modules/test_zos_stat_func.py

[Enhancement] [zos_stat] Add support for aliases

---

changelogs/fragments/2068-zos_data_set-Removed-Extra-Validation.yml
changelogs/fragments/2068.yml
plugins/module_utils/data_set.py

Removed Extra Validation Step for mulkti volume use cases
#1263 
data_set.py
```paste below
```

Removed extra validation step for multi volume use cases

---

changelogs/fragments/2073-zos_find-finding-migrated-datasets.yml
plugins/modules/zos_find.py
tests/functional/modules/test_zos_find_func.py

Enhancements - Optionally find migrated datasets #1136 and find different types of datasets at the same time #2067
zos_find
- Migrated datasets will be retrieved by comparing results of dls -m and dls -l commands.
- C(resource_type) changed from str to list to support different types of datasets at the same time.
- Handled excludes, examined params.
- Added new option migrated_type
- Added testcases and updated documentation

[Enhancement] [zos_find] find migrated datasets and find different types of datasets at the same time

---

changelogs/fragments/2098-docs-migrated-data-sets-examples.yml
docs/source/modules/zos_copy.rst
docs/source/modules/zos_mvs_raw.rst
docs/source/modules/zos_tso_command.rst
plugins/modules/zos_copy.py
plugins/modules/zos_mvs_raw.py
plugins/modules/zos_tso_command.py

Fixes #1663.
- zos_copy
- zos_mvs_raw
- zos_tso_cmd

[Documentation] [zos_copy] [zos_mvs_raw] [zos_tso_cmd] Tell users how to recall migrated data sets

---

.github/ISSUE_TEMPLATE/bug_issue.yml
.github/ISSUE_TEMPLATE/collaboration_issue.yml
.github/ISSUE_TEMPLATE/doc_issue.yml
.github/ISSUE_TEMPLATE/enabler_issue.yml
.github/ISSUE_TEMPLATE/enhancement_feature.issue.yml

Updated Github templates. Added zos_stat and removed unsupported collection and ZOAU versions.
- Github Pull Request

Updated github templates

---

CHANGELOG.rst
changelogs/changelog.yaml
docs/source/life-cycle.rst
docs/source/modules/zos_mount.rst
docs/source/release_notes.rst
galaxy.yml
meta/ibm_zos_core_meta.yml

Brings back all v1.14.0GA changes to dev branch.
- Release Pull Request

Cherry pick v1.14.0 GA into dev

---

.github/ISSUE_TEMPLATE/bug_issue.yml
.github/ISSUE_TEMPLATE/collaboration_issue.yml
.github/ISSUE_TEMPLATE/doc_issue.yml

Update templates issue

---

changelogs/fragments/2213-test-case-conditional-failure-2-19.yml
tests/functional/modules/test_zos_copy_func.py
tests/functional/modules/test_zos_job_submit_func.py
tests/functional/modules/test_zos_script_func.py
tests/functional/modules/test_zos_unarchive_func.py

Some test cases that involve the creation of playbooks on the fly were failing in ansible 2.19 due to a conditional error.
```paste below
```

Conditionals failure when executing playbooks in test cases

---

changelogs/fragments/2245-zos_tso_command-interface-update.yml
plugins/modules/zos_tso_command.py
tests/functional/modules/test_zos_tso_command_func.py

Updated zos_tso_command module interface.
Fix #2163 

[Enhancement][zos_tso_command][2.0] Update module interface 

---

changelogs/fragments/2250-Update_zos_apf_interface.yml
plugins/modules/zos_apf.py
tests/functional/modules/test_zos_apf_func.py
tests/functional/modules/test_zos_replace_func.py

[Enabler][2139]update_zos_apf_interface

---

changelogs/fragments/2253-zos_lineinfile-interface-update.yml
changelogs/fragments/2258-zos_lineinfile-cleanup-file.yml
plugins/modules/zos_lineinfile.py
tests/functional/modules/test_zos_lineinfile_func.py

Renamed ``return_content`` return value to ``stdout``.
Added new return values:
``stdout_lines``
``stderr_lines``
Fix #2115 
zos_lineinfile

[Enhancement][2.0][zos_lineinfile] Update module interface

---

tests/helpers/users.py

Removes unnecessary comment. 
There is no git issue associated intentionally. 

Update spi comment from source.

---

changelogs/fragments/2290-update-verb-options.yml
plugins/action/zos_copy.py
plugins/action/zos_fetch.py
plugins/action/zos_script.py
plugins/action/zos_unarchive.py
plugins/module_utils/copy.py
plugins/modules/zos_copy.py
plugins/modules/zos_fetch.py
tests/functional/modules/test_zos_copy_func.py
tests/functional/modules/test_zos_fetch_func.py
tests/functional/modules/test_zos_mount_func.py
tests/functional/modules/test_zos_unarchive_func.py

Changed keywords is_binary and is_executable to not use verbs

---

.github/workflows/ac-module-doc.yml
CHANGELOG.rst
README.md
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
docs/source/life-cycle.rst
docs/source/modules/zos_replace.rst
docs/source/release_notes.rst
galaxy.yml
meta/ibm_zos_core_meta.yml
plugins/action/zos_fetch.py
plugins/module_utils/dd_statement.py
plugins/modules/zos_replace.py
tests/functional/modules/test_zos_find_func.py
tests/functional/modules/test_zos_lineinfile_func.py
tests/helpers/volumes.py

Merge 1.15.0 release into staging-v1.15.0-beta.1
- Release Pull Request

Merge 1.15.0 GA into staging-v1.16.0-beta.1
