ansible-collections/ibm_zos_core

plugins/module_utils/better_arg_parser.py
This PR relates to NAZARE-129. Because of the often complex nature of z/OS operations, arguments often have dependencies on each other. For that reason, I have created an additional argument parser to be used in conjunction with Ansible's default parser build in to *module_utils.basic.AnsibleModule*.
better_arg_parser.py
Features:
- Arguments dependencies on other arguments
- Multiple levels of nested arguments (dict of dict, list of dict, dict of lists, etc.)
- Type checking and modification
- Default value handling
- Required arguments
- Providing list of valid choices
- Argument aliases
- Custom functions for type checking, defaults, and required arguments.
- Can leverage contents of arguments specified as dependencies.
=> added arg parser to module_utils

plugins/module_utils/job.py, plugins/modules/zos_job_output.py, plugins/modules/zos_job_submit.py
There was an issue in *zos_job_submit* that caused failure when attempting to retrieve the output of a job with a large log size. This PR removes the offending API and replaces it with a shared job output retrieval utility.
- Hotfix Pull Request
- modules/zos_job_submit module 
- modules/zos_job_output module
- module_utils/job
Submit a job which generates a large amount of output to the job log. (eg. DBDGEN) using *zos_job_submit*
=> refactor and patch job output checking

plugins/module_utils/job.py, plugins/modules/zos_job_submit.py
Fixes #488 which was resulting in no job summary output being returned when `return_output=false` for the zos_job_submit module. Now, job output should be returned correctly.
```yaml
Before change output:
changed: [zvm] => changed=true 
duration: 0
invocation:
module_args:
encoding: UTF-8
location: USS
max_rc: 0
return_output: true
src: /tmp/ansible/jcl/HELLO
volume: null
wait: true
wait_time_s: null
message:
stdout: Submit JCL operation succeeded.
After change output:
changed: [zvm] => changed=true 
duration: 0
invocation:
module_args:
encoding: UTF-8
location: USS
max_rc: 0
return_output: true
src: /tmp/ansible/jcl/HELLO
volume: null
wait: true
wait_time_s: null
jobs:
- class: R
content_type: JOB
ddnames:
- byte_count: '774'
content:
- '1                       J E …
```
=> updated job output for improved DD handling

docs/source/conf.py, docs/source/installation.rst, docs/source/plugins.rst, plugins/modules/zos_job_output.py, plugins/modules/zos_job_query.py
This update removes the unnecessary return value "original_message". There is no need to return the original options , there are other ways to access this and don't see any need to parse this value out from a response.  
Module: zos_job_query
=> remove original_message return parameter

galaxy.yml
Fixes README to point to .md instead of .rst
Fixes the long tag
Contributed by @thedoubl3j
=> Corrected README to point to MD, and long tag removed

plugins/module_utils/better_arg_parser.py
Add the following two arg types to BetterArgHandler::
- data_set_or_path_type
- encoding_type
_data_set_or_path_type_: A handler for arguments that can be either data sets or paths, (e.g. `USER.PROCLIB` and `/etc/profile` are both valid
_encoding_type_: A handler for arguments that specify encoding, (e.g. `IBM-037`, `ISO-88559-1`)
=> Add two additional arg types to BetterArgHandler

plugins/module_utils/data_set_utils.py
DataSetUtils can be used to perform the following:
- Determine data set type
- Determine whether a data set exists (works for VSAM and Non-VSAM alike)
- Create a temporary data set
- Retrieve data set volume  name
- Retrieve data set record format
- Retrieve data set record length
data_set_utils
=> Data Set Utility for Common Data Set Related Tasks

plugins/modules/zos_operator_action_query.py
Fixes #1160 in Jira. In zos_operator_action_query, capture group for job name was set to noncapture group, as well as another capture group that should not have been present, was causing incorrect capture of text unrelated to job name.
- /plugins/modules/zos_operator_action_query.py
```paste below
```
=> bugfix for job name capture group

plugins/module_utils/import_handler.py, plugins/modules/zos_data_set.py, plugins/modules/zos_job_query.py, plugins/modules/zos_job_submit.py, plugins/modules/zos_operator.py, plugins/modules/zos_operator_action_query.py
This PR addresses #1648 in Jira. PR adds a new shared utility MissingZOAUImport to module_utils and updated modules to use the utility. Any method call on an MissingZOAUImport object will raise an ImportError with the message 
> ZOAU is not properly configured for Ansible. Unable to import zoautil_py. Ensure environment variables are properly configured in Ansible for use with ZOAU.
This is an improvement over the old method, which by comparison, set the expected ZOAU import names to an empty string when ZOAU import errors occurred. The old method has led to  confusion from users whose environment variables are not properly configured.
In addition, one error message return format was changed in zos_job_submit to prevent an ambiguous error message from being returned in place of a …
=> Better ZOAU import missing messages

plugins/modules/zos_operator_action_query.py, tests/functional/modules/test_zos_operator_action_query_func.py
Fixes #1698 in Jira. This PR changes the behavior of zos_operator_action_query to return an empty list for `actions` when no action messages are found. This differs from old behavior which would raise an exception if no messages were found. 
I also modified an exception string response to match behavior provided by other modules.
- Update Pull Request
- plugins/modules/zos_operator_action_query.py
=> changed behavior on failure

plugins/module_utils/job.py, plugins/modules/zos_job_output.py, plugins/modules/zos_job_query.py, plugins/modules/zos_job_submit.py, tests/conftest.py
This module fixes #1661 and #1704 in Jira, as well as fixes #62  in GitHub.
Both modules were using the ZOAU Jobs.list() method, which does not support querying on jobs by ID outside of those owned by the user. This can be done by calling Jobs.list() with no arguments then parsing, but that is excessive. 
This PR removed the use of Jobs.list() from the modules and replaces it with calls to the shared job utility in module_utils. In addition, a new function, job_status, was added to the shared job utility to simplify retrieval of basic status information for jobs without spending the effort or computationfinding,  printing and parsing all the DD output.
Other changes:
- enhanced shared job library to no longer require AnsibleModule object to be provided as an argument
- enhanced shared job …
=> Bugfix/1661 & 1704 fix query of job for different user zos_job_submit and zos_job_action_query

plugins/modules/zos_operator.py
Add an example for zos_operator that demonstrates a command that needs to be escaped to execute.
=> Add an example that requires a command to be escaped

ansible.cfg, collections/requirements.yml
Add required requirements file and additional ansible.cfg file to simplify collection sample usage in AWX and Ansible Tower
- Update Pull Request
- collections/requirements.yml tells AWX/Tower what collections are used inside of the project
- ansible.cfg is required at root because AWX/Tower always calls playbooks from project root folder
=> add out-of-box awx support

plugins/module_utils/backup.py, plugins/modules/zos_encode.py, tests/functional/modules/test_zos_encode_func.py
Additional tests and fixes related to #1906 in Jira. Fixes logic error which would result in no backup path returned even even backups were created. In addition, adds correct extension to backup name response when compression is specified.
=> minor fixes and additional tests for zos_encode

docs/templates/module.rst.j2
The template used to create the web docs had different results for different people for unknown reason, the fix is to put in some additional logic to sanitize the input and generation.
The second issue is the return values in the return block spacing was off adding new lines between each value
=> Fixes spacing in RETURN values and formatting

plugins/module_utils/job.py
Fixes #2006 in jira and possibly another issue in GitHub. Two separate users have been experiencing an error when attempting to retrieve job information from SDSF using only a job ID. The problem was traced back to the SDSF `FILTER` command not returning any job information if an owner or jobname was not provided as well.
This update changes default search behavior for underlying SDSF calls to `job_name='*'` and `owner='*'`. This fixes the issue on at least one user's system.
- plugins/module_utils/job.py
=> fix job utility to work on all z/OS systems

plugins/modules/zos_job_submit.py
Fixes bug resulting in failure when no encoding specified for zos_job_submit.
- plugins/modules/zos_job_submit.py
To reproduce, run zos_job_submit without any encoding argument provided.
```paste below
```
=> fix issue when no default encoding specified

plugins/module_utils/encode.py
`uss_convert_encoding` does not close file descriptor returned by `mkstemp` function, causing too open file descriptors on large conversion workloads
encode
=> Encode util close file descriptor

plugins/modules/zos_operator.py
Fixes issue #2814 in Jira, "Certain operator commands result in heap error zos_operator". This PR removed usage of ZOAU Python API previously used to run operator commands, this works around the heap issues that were encountered previously with the ZOAU Python API. 
- plugins/modules/zos_operator.py
=> remove ZOAU Python API deps for zos_operator

plugins/action/zos_copy.py, plugins/action/zos_fetch.py, plugins/modules/zos_copy.py, plugins/modules/zos_fetch.py, tests/functional/modules/test_zos_copy_func.py, tests/functional/modules/test_zos_fetch_func.py
Often, the default port 22 may not be available to perform data transfer. The `sftp_port` parameter lets the user specify which port should be used to connect to the remote sftp server.
zos_fetch, zos_copy
=> Specify SFTP port for fetch and copy

playbooks/host-setup.yaml, playbooks/templates/host-vars.j2, playbooks/templates/test-vars.j2
This PR fixes a small issue with file extensions in host-setup.yaml, I had updated the file extensions of task files to `.yaml` from `.yml` but forgot to update the paths in host-setup.yaml.
=> Update file extensions in host-setup.yaml

docs/source/modules/zos_copy.rst, docs/source/modules/zos_fetch.rst, plugins/action/zos_copy.py, plugins/action/zos_fetch.py, plugins/modules/zos_copy.py, plugins/modules/zos_fetch.py
This PR Fixes #150 where zos_fetch and zos_copy fails if there is a pre-login prompt when connecting to the remote z/OS server through ftp. The fix adds a new parameter that allows the user to override the default behavior of failing when `stderr` of sftp command is non-empty.
zos_copy, zos_fetch
=> copy/fetch: Ignore stderr

plugins/modules/zos_operator_action_query.py
This PR fixes a bug in zos_operator_action_query which results in some outstanding messages not being returned to the user. I have updated the regex and rewrote some of the logic to handle multiline messages.
- plugins/modules/zos_operator_action_query.py
=> Bugfix: zos operator action query not returning all outstanding messages

plugins/module_utils/dd_statement.py, plugins/modules/zos_mvs_raw.py
This PR fixes #3375 in Jira. zos_mvs_raw will now ignore any optional parameters that are provided to a STEPLIB DD statement. In addition, a new parameter, `verbose`, has been added to assist users in debugging issues when calling programs using zos_mvs_raw.
- plugins/module_utils/dd_statement.py - don't build out parameter strings when DD is a STEPLIB DD
- plugins/modules/zos_mvs_raw.py - add verbose argument
=> Add verbose support and steplib fix

plugins/action/zos_copy.py, plugins/action/zos_fetch.py, plugins/action/zos_job_submit.py
This PR fixes a bug which causes action plugins to fail when collections are referenced using fully qualified collection names instead of playbook level imports. Since playbook level imports do not work in roles, this causes any of our modules that use action plugins to fail when used inside roles.
=> add FQCN to action plugins

docs/source/modules/zos_copy.rst, docs/source/modules/zos_fetch.rst, docs/source/release_notes.rst, plugins/action/zos_copy.py, plugins/action/zos_fetch.py, plugins/module_utils/data_set.py, plugins/module_utils/encode.py, plugins/modules/zos_copy.py, plugins/modules/zos_fetch.py
This PR introduces a few enhancements and a bugfix
Enhancements:
- Use `ansible_port` as the default sftp port. This means that the user does not have to explicitly specify sftp port. The `sftp_port` parameter is still there if the user really wants to specify it.
- The user no longer has to specify `encoding` when copying/fetching text data. The modules are able to discover the default remote system charset to use. The `encoding` parameter is still there if the user wants to use different charsets.
Bugfixes:
- When copying a data set member to a USS file, the data appears to be duplicated. This is happening because the module uses USS `cp` command with `-F rec` flag. This has been changed to use ZOAU copy API.
zos_fetch, zos_copy, encode
=> Copy + Fetch Update

plugins/action/zos_copy.py, plugins/action/zos_fetch.py, plugins/module_utils/encode.py, plugins/module_utils/system.py, plugins/modules/zos_copy.py, plugins/modules/zos_fetch.py, tests/conftest.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt
Currently, the copy and fetch modules use `locale` command to discover default remote charset. However, USS would return IBM-1047 as output for that command, which is not accurate for MVS data sets. MVS data sets are almost always encoded in IBM-037. This PR fixes this issue.
zos_copy, zos_fetch
=> Default MVS charset should be IBM-037

docs/source/conf.py, docs/source/release_notes.rst, galaxy.yml, plugins/module_utils/encode.py, plugins/module_utils/system.py, plugins/modules/zos_copy.py, plugins/modules/zos_fetch.py
Version 1.2.1
=============
Notes
-----
* Update required
* Module changes
* Noteworthy Python 2.x support
* encode - removed TemporaryDirectory usage.
* zos_copy - fixed regex support, dictionary merge operation fix
* zos_fetch - fix quote import
* Collection changes
* Beginning this release, all sample playbooks previously included with the
collection will be made available on the  [samples repository](https://github.com/IBM/z_ansible_collections_samples/blob/master/README.md). The
[samples repository](https://github.com/IBM/z_ansible_collections_samples/blob/master/README.md) explains the playbook concepts,
discusses z/OS administration, provides links to the samples support site,
blogs and other community resources.
* Documentation changes
* In this release, documentation related to …
=> Release v1.2.1

plugins/modules/zos_tso_command.py
This PR fixes #193 in GitHub. After these updates, zos_tso_command no longer relies on a REXX script to build JSON output, instead building a python dictionary independently of the REXX script. This will fix any issues caused by invalid characters encountered when loading JSON data.
- plugins/modules/zos_tso_command.py - improve REXX script output
=> fix zos_tso_command

plugins/module_utils/data_set.py, plugins/modules/zos_data_set.py
This PR fixes #3857 in Jira. This PR fixes a bug that sometimes occurs when attempting to catalog a data set that does not exist. The catalog command will run successfully and "catalog" the data set, but the data set will not actually exist. This leads to unexpected behavior in future commands that see the "existent" data set but cannot use it.
- plugins/module_utils/data_set.py - fix logic for ensuring data set present
- plugins/modules/zos_data_set.py - fix formatting
=> catalog only when we are sure data set exists on volume

plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
This PR fixes NAZARE-3862: the module should fail when encountering a non-zero return code from ZOAU copy API and display stdout and stderr information.
zos_copy
=> fail on non-zero zoau copy return code

plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py, tests/functional/modules/test_zos_fetch_func.py
This PR updates the test cases of zos_fetch and zos_copy to have data set names as variables instead of hard coding them. This would make changing data set names easier later down the road.
zos_copy, zos_fetch
=> Updated test cases for zos_copy/fetch + bugfix

tests/dependencyfinder.py
This PR updates dependencyfinder.py's default branch name for comparisons to `origin/dev`, this will work more reliably than `dev` which was previously used.
=> add origin/ to default branch name

tests/dependencyfinder.py
This PR fixes a small bug in dependencyfinder.py which prints a newline when no tests are found, this would cause some unexpected behavior when checking if any tests need to run.
=> fix newline print if nothing found

docs/templates/module.rst.j2
This was encountered with when we were on-boarding zHMC where they had a module option that spanned a range. I saw nothing technically incorrect in this option spec and found that our Jinja template would error on a default case when it encountered a default as such below.
```
type: list
elements: int
required: false
default: [0,-1]
```
```paste below
```
=> Update template to support complex list with elements

docs/templates/module.rst.j2
This PR addresses issue #219.
For details, see the commit message.
=> Fixes #219: Support for choosing parm odering in module template

docs/templates/module.rst.j2
Fixes #224:
The module.rst.j2 template supported only a single sample in the 'sample' attribute of a return property. This change adds support for multiple samples by specifying child attributes 'sample1', 'sample2', etc under the 'sample' attribute. This is consistent with how the ibm_zosmf collection supports it, but the solution in addition takes care to distinguish str/int types and complex types consistent with how it is done for single samples.
* docs/templates/module.rst.j2
**Note:** This PR is on top of PR #223 to avoid merge effort.
=> Fixes #224: Support for multiple samples in module return properties

docs/templates/module.rst.j2
Fixes #226: 
Currently, the module.rst.j2 template does not show the 'elements' attribute for return value properties. It does show it for input parameters.
This change adds support for showing the 'elements' attribute for return value properties, if specified.
* docs/templates/module.rst.j2
**Note:** This PR is on top of PR #223 to avoid merge effort.
=> Fixes #226: Support for showing list elements in module return values

docs/templates/module.rst.j2
Fixes #228:
The current module template generates long single-line JSON representations of sample values of return value properties. This change formats them as multi-line JSOn with an indentation of 4.
The code-block used for these JSOn samples is marked up to have json content, producing a nicer coloring of the samples.
* docs/templates/module.rst.j2
**Note:** This PR is on top of PR #225 to avoid merge conflicts.
=> Fixes #228: Support for multi-line JSON samples in module template

docs/templates/module.rst.j2
This update allows for documentation on options to be skipped such that no documentation is generated for a module. This can come in handy in cases where we want to avoid displaying an option in our HTML docs. Although, this does nothing in terms of ansible_doc as the option will still show up with `ansible-doc` but we predict that most if not all of our users are using our online docs and not the command line. 
=> Add support to template to skip options that begin with an underscore

galaxy.yml
Ansible 2.10 adoption will only be a matter of time; this change leverages the upcoming build_ignore for directories and files, long anticipated. This update will not impact builds performed on ansible 2.9. 
This update will not benefit collections built with Ansible 2.9.x but as the pull request states, it is 'readiness' for Ansible 2.10.
Our Ansible Z collections for both Galaxy and Hub are **currently built on 2.9.x** to **remain compatible** with Ansible Hub requirements. 
**NOTE**: We have been seeing this warning since we began using build_ignore to exclude files for a year now. The warning causes no issues for builds done with Ansible 2.9.x which is when it appears and my guess it is because build_ignore is officially supported in Ansible …
=> Updated build_ignore for Ansible 2.10 readiness and additional updates

galaxy.yml
Updating the galaxy.yml to ensure the Jenkinsfile is not included in our collection builds. Note; this will only be true if we build with Ansible 2.10 were `build_ignore` is supported. 
=> Added Jenkinsfile to the ignore to exclude from collection builds

docs/source/release_notes.rst, galaxy.yml, meta/ibm_zos_core_meta.yml
This change supports the doc generation that happens on Automation Hub and provides a fix such that the tooling can not have a python based module to extract doc from instead of a REXX based module (zos_ping). 
This also changes the execution order such that REXX based modules are prioritized over other such as python.
=> Changes made for module zos_ping to support doc generation

plugins/modules/zos_job_query.py
This change supports both 5 and 7 digit job IDs. 
JobIDs can come in one of two formats:
`<3 chars><5 digits>` or <1 chart><7 digits>` depending on the number of jobs in JES2 and the systems configuration. 
More on [JES2](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.ieaa600/iea3a6_Obtaining_a_job_identifier.htm) be sure to note the section:
```
"When job numbers are potentially greater than 99,999, the format for job numbers is as follows: if the maximum allowed job number (high value of the JOBDEF RANGE= statement) is above 99,999, the job number format is J0nnnnnn." 
```
**zos_job_query**
Pretty straight forward change, simple regex and doc update. 
Waiting on a fixtest before merging.
Unable …
=> Update to support job id up to 7 numeric positions

plugins/modules/zos_mvs_raw.py
Removed the duplicate "name" entry from the examples. Defect fix for https://jsw.ibm.com/browse/NAZARE-6112.
```paste below
```
=> Update zos_mvs_raw.py - removed duplicate name entry from the examples. 

plugins/module_utils/job.py
This commit fixes the bug such that when Job content is returned by the `zos_job_output` module (or any module using the jobs.py code to return job content) its not truncated by the incorrect use of of the record count variable. 
Record count does not equate to the lines in job content, the job content is 1 entry with regard to records from the record count, the job content just have its own iterator. No maximum has been set for this as I don't feel we don't have the justification to limit this and would rather the customer receive the full ouput. Should we ever need to limit you can set a REXX limiter like so `isflinelim = 500` , more on REXX and isfline [here](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3sc279028/$file/ …
=> Update common code used to obtain job content such it is not trucated by the unrelated record count

plugins/modules/zos_operator_action_query.py, tests/functional/modules/test_zos_find_func.py
The operator action query module operates by running two hard coded commands (`d r,a,s` , `d r,a,jn`) which are executed by the ZOAU opercmd dependency. 
In some queries for an operator action if they are not job related , the job name would come back null since obviously its unrelated to a WTO which has no associated job name, this update removes the property from the response. 
The second issue was reported and unpronounceable by the client and our development but the source of the issue could be aided for future occurrences by propagating the return code coming from the command execution. The two commands used are hard coded and not the issue, the customer was able to run them after the error and they were not the source nor likely on a 55 yr old OS :-). I double checked all the …
=> Bug fix not propagating non zero return codes and under certain cases job_name is null for operator action query

docs/source/release_notes.rst, galaxy.yml, meta/runtime.yml, plugins/action/zos_fetch.py, plugins/modules/zos_copy.py, plugins/modules/zos_data_set.py, plugins/modules/zos_fetch.py, plugins/modules/zos_find.py, plugins/modules/zos_job_output.py, plugins/modules/zos_job_query.py, plugins/modules/zos_job_submit.py, plugins/modules/zos_mvs_raw.py, plugins/modules/zos_ping.py, tests/functional/modules/test_zos_copy_func.py, tests/functional/modules/test_zos_find_func.py, tests/sanity/ignore-2.11.txt
Fixes both JIRA-8779 and JIRA-8780, bugs reported by clients about the temporary files and cleanup of the zos_copy module. Branched out from the v1.3.1 tag to create a patch for that version.
zos_copy
JIRA-8779 fixes the deletion of files already in a directory when Ansible is trying to copy new files into it.
JIRA-8780 fixes when Ansible is trying to clean up temporary files that are not from the zos_copy module at the end of execution.
=> Bugfix/8779 8780/zos copy cleanup bugs for v1.3.1.1

plugins/connection/zos_ssh.py
There was a bug in Ansible that would result in task retries overriding the connection retries. Using a different name for the connection retries setting avoids this issue on versions of Ansible that are missing the bug fix.
`plugins/connection/zos_ssh.py`
Related to https://github.com/ansible/ansible/pull/75155.
=> zos_ssh - rename retries setting

changelogs/fragments/339-copy-sub-directories.yml, plugins/action/zos_copy.py, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
Addresses a client's issue when trying to copy a local directory that has multiple subdirectories in its root into USS.
zos_copy
The module already validates that the user is not trying to copy subdirectories into a PDSE, but this validation also affects trying to copy into USS. Since its possible to copy a complex tree structure into USS (and, in fact, the module already does this when using a remote source), the module now allows to copy subdirectories into USS from a local source.
When using `force=true` in the module parameters while copying a directory into USS, the module now returns `changed=true`.
=> [zos_copy] Copy subdirectories when copying into USS

changelogs/fragments/336-update-zos_copy-uss-to-pdse.yml, plugins/modules/zos_mvs_raw.py, tests/dependencyfinder.py, tests/functional/modules/test_zos_copy_func.py, tests/functional/modules/test_zos_mvs_raw_func.py, tests/helpers/zos_blockinfile_helper.py
Fixes item 7525 on Jira by changing the way the argument parser treats the default value for the `dds` parameter in the `zos_mvs_raw` module.
`zos_mvs_raw`
This bug was reported to happen while trying to run the `IEFBR14` command in a playbook without specifying any DD statements. The command by itself doesn't need any DD statements but the module nonetheless throws an exception if you don't specify at least a dummy dataset. Additionally, the documentation states that the `dds` parameter is optional, so the argument parser was changed accordingly.
=> Bugfix/7525/changed default value for dds in zos_mvs_raw

changelogs/fragments/345-update-encoding-options.yml, plugins/modules/zos_encode.py, tests/dependencyfinder.py, tests/functional/modules/test_zos_copy_func.py, tests/functional/modules/test_zos_encode_func.py, tests/helpers/zos_blockinfile_helper.py, tests/helpers/zos_lineinfile_helper.py
Addresses JIRA-1978, an enhancement for the `zos_encode` module. Instead of using `from_encoding` and `to_encoding` to define the encoding conversion, the module now uses the interface found in all the other modules of the collection, i.e., an `encoding` parameter with suboptions `from` and `to`.
zos_encode
Before this change, all other modules of the collection that can handle encoding conversion between files and datasets used the same interface for defining the way the conversion happened, except for `zos_encode`. The purpose of this PR is to bring consistency across the interfaces of all modules in the collection.
@fernandofloresg brought up a really important point about supporting the old interface for users that already have working playbooks. Should we keep …
=> Changed the encoding options to suboptions

changelogs/fragments/389-fixes-zos-operator-timeout-option.yml, plugins/modules/zos_operator.py, tests/functional/modules/test_zos_operator_func.py
After ZOAU implemented timeout option in opercmd support was missing from zos_operator. Changed the opercmd.execute_command call to use the latest interface and explicitly provide the timeout value, had to be done this way since zoau python utils does a validation in this value over kwargs. 
Added the case when wait_time_s is 0 to default to 1 and be true to the docs "When set to 0, the system default is used".
Also changed the test to now validate for timeouts and enabled the quick delay test.
**Update, in addition to the original issue these updates are have included in this PR:**
- bugfixes:
- ibm_zos_operator - fixed such that specifying wait_time_s would throw an error (original issue in this PR)
- ibm_zos_operator - fixed case sensitive error checks, invalid, error & unidentifiable …
=> [Bug] zos_operator throws TypeError when wait_time_s is specified 

changelogs/fragments/400-fixes-verbose-trailing-lines.yml, plugins/modules/zos_operator.py, tests/functional/modules/test_zos_operator_func.py
This fixes the issue where the verbosity was not returned when a user set it to True. It also fixes the extra empty lines returned in the response in the content field. 
It also updates the documentation to remove the security references under verbosity as that no longer supported content. 
Fixes #397 
Fixes #399 
`zos_operator`
Before:
```
ok: [zvm] => {
"result": {
"changed": true,
"cmd": "d t",
"content": [
"EC33017A   2022245  13:14:52.00             ISF031I CONSOLE OMVS0000 ACTIVATED",
"EC33017A   2022245  13:14:52.00            -D T ",
"EC33017A   2022245  13:14:52.00             IEE136I LOCAL: TIME=13.14.50 DATE=2022.245  UTC: TIME=20.14.50 DATE=2022.245",
"",
""
],
"elapsed": 9.16,
"failed": false,
"rc": 0,
"wait_time_s": 10
}
}
```
After:
```
ok: [zvm] => { …
```
=> Fixes zos_operator verbosity and excessive lines in content returned

changelogs/fragments/393-tmphlq-dd-statements.yml, plugins/module_utils/dd_statement.py, plugins/modules/zos_mvs_raw.py, tests/dependencyfinder.py
Discovered that during the implementation of tmphlq there were some missing DDStatements in zos_mvs_raw that were missing the tmphlq when calling Datasets.create_temp()
Added TMPHLQ as a parameter for StdinDefinition and OutputDefinition **defaulting as an empty string**, this is different as how tmphlq is defaulted to None in other sections of the code because the hlq parameter of create_temp is a string and defaults as empty too, so I wanted to keep consistency with that interface.
Also, since tmphlq was now added to more than dd type I abstracted the assignment into a function called set_extra_attributes_in_dd to avoid overpopulating the build_data_definition function with tmphlq assignments, figured that we could add extra attributes there too if needed in the future(maybe pass it as …
=> Bugfix/393/tmp hlq ddstatements: Adds tmphlq to create_temp datasets in DDStatements.

changelogs/fragments/462-copy-fetch-submit-utils.yml, changelogs/fragments/462-set-mode-directories-files.yml, docs/source/modules/zos_apf.rst, docs/source/modules/zos_mvs_raw.rst, docs/source/release_notes.rst, docs/source/requirements-single.rst, galaxy.yml, meta/ibm_zos_core_meta.yml, plugins/connection/zos_ssh.py, plugins/module_utils/job.py, plugins/modules/zos_apf.py, plugins/modules/zos_backup_restore.py, plugins/modules/zos_blockinfile.py, plugins/modules/zos_copy.py, plugins/modules/zos_data_set.py, plugins/modules/zos_encode.py, plugins/modules/zos_fetch.py, plugins/modules/zos_job_submit.py, plugins/modules/zos_lineinfile.py, plugins/modules/zos_mvs_raw.py, tests/dependencyfinder.py, tests/functional/modules/test_zos_copy_func.py, tests/helpers/zos_blockinfile_helper.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
Fixes for 
- #411 (mode gets ignored when copying between directories)
- #412 (unsupported parameters in zos_copy in Ansible 2.11)
- #354 `zos_job_output` had DD's truncated, fix was in module_utils `job.py`
- #495 `zos_ssh` used by with `zos_ping` fails with an attribute error when used with `ansible-core` v2.11
zos_copy
For #411: When using `mode` in zos_copy and copying between directories, the given permissions are applied to the destination directory and any files that were not already present in it. Preexisting files and subdirectories are left with the same permissions they had before running the module.
For #412: `force` was added to the `arg_spec` of the module.
=> [Bug] [zos_copy] Bugfixes for v1.3.6

changelogs/fragments/507-display-specific-ddname.yml, docs/source/release_notes.rst, plugins/module_utils/job.py, tests/functional/modules/test_zos_job_output_func.py
Fixed a typo in module_utils/job.py:
module_utils/job.py line 59 in 1.3.4 code reads:
dd_name = parsed_args.get("ddname") or ""
To
dd_name = parsed_args.get("dd_name") or ""
Fixes https://github.com/ansible-collections/ibm_zos_core/issues/329 on support 1.3.x branch
This was cherry-picked from a prior release to forward fix the 1.4.0-beta.2 release. 
These are the commits cherry-picked:
https://github.com/ansible-collections/ibm_zos_core/pull/334/commits/31f8eb3b48c99c12f6c74ab0db34e59c04010c00
https://github.com/ansible-collections/ibm_zos_core/pull/334/commits/dd7b3f51115b275610ee47fb26d4f94e58adb6a7
```paste below
```
=> Bugfix - corrects the dd_name used in jobs.py

changelogs/fragments/511-update-ccsid-type-int.yml, plugins/modules/zos_mount.py, tests/dependencyfinder.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.9.txt
This bugffix addresses zos_mount. It fixed option `tag_ccsid` to correctly allow for type int.
It addresses issue #506 
It also updates the dependency finder such that it can support pull request base branches that are not only `origin/dev`.
It addresses also issue #508 
=> Bugfix [zos_mount] ccsid type is string when it should be int, update dependency finder

tests/functional/modules/test_zos_job_output_func.py
This corrects the name of a job in a test case, it was accidently named to match the JCL instead of the Jobname; for now this is a simple fix, it would be better if the JCLs were named to match the JOB names to avoid confusion.
This fixes #509 
=> Fix job name in zos_job_output test case

changelogs/fragments/513-zos_ssh-support-ansible-2.11.yml, plugins/connection/zos_ssh.py, tests/dependencyfinder.py
Fixes the issue in #495 
Where when using ansible-core 2.11 and `zos_ping` which requires the `zos_ssh` connection such that you receive an error
```
AttributeError: module 'ansible.constants' has no attribute 'ANSIBLE_SSH_CONTROL_PATH_DIR'.
```
`zos_ssh` affects `zos_ping`
Tested it in both ansible 2.9 and ansible-core 2.11.
Result for ansible-core 2.11:
```
(ansible-doc) ddimatos:[ ~/git/github/playbooks ]ansible --version
ansible [core 2.11.12]
config file = /Users/ddimatos/git/github/playbooks/ansible.cfg
configured module search path = ['/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules']
ansible python module location = …
```
=> Update the forked ssh code to support both ansible 2.9 an 2.11

docs/source/release_notes.rst, docs/source/requirements_managed.rst, plugins/action/zos_fetch.py, plugins/action/zos_job_submit.py, plugins/connection/zos_ssh.py, plugins/module_utils/backup.py, plugins/module_utils/zos_mvs_raw.py, plugins/modules/zos_apf.py, plugins/modules/zos_blockinfile.py, plugins/modules/zos_copy.py, plugins/modules/zos_fetch.py, plugins/modules/zos_job_output.py, plugins/modules/zos_job_submit.py, plugins/modules/zos_lineinfile.py, plugins/modules/zos_operator.py, plugins/modules/zos_tso_command.py, tests/dependencyfinder.py
Version 1.3.6
=============
What's New
----------
* Bug Fixes
* Modules
* ``zos_copy`` fixes a bug that when a directory is copied from the
controller to the managed node and a mode is set, the mode is now applied
to the directory on the controller. If the directory being copied contains
files and mode is set, mode will only be applied to the files being copied
not the pre-existing files.
* ``zos_copy`` - fixes a bug where options were not defined in the module
argument spec that will result in error when running `ansible-core` v2.11
and using options `force` or `mode`.
* ``zos_copy`` - was enhanced for when `src` is a directory and ends with "/",
the contents of it will be copied into the root of `dest`. It it doesn't
end with "/", the …
=> Release v1.3.6

CHANGELOG.rst, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, changelogs/fragments/496-copy-support-directories.yml, changelogs/fragments/v1.0.0_summary.yml, changelogs/fragments/v1.1.0_summary.yml, changelogs/fragments/v1.2.1_summary.yml, changelogs/fragments/v1.3.0_summary.yml, changelogs/fragments/v1.3.1_summary.yml, changelogs/fragments/v1.3.3_summary.yml, changelogs/fragments/v1.3.4_summary.yml, changelogs/fragments/v1.4.0-beta.1_summary.yml, changelogs/fragments/v1.4.0-beta.2_summary.yml, docs/source/release_notes.rst, plugins/modules/zos_fetch.py
Version 1.4.0-beta.2
===============
* Bug fixes and enhancements
* Modules
* ``zos_copy``
* introduced an updated creation policy referred to as precedence rules
that if `dest_data_set` is set, it will take precedence. If
`dest` is an empty data set, the empty data set will be written with the
expectation its attributes satisfy the copy. If no precedent rule
has been exercised, `dest` will be created with the same attributes of
`src`.
* introduced new computation capabilities that if `dest` is a nonexistent
data set, the attributes assigned will depend on the type of `src`. If
`src` is a USS file, `dest` will have a Fixed Block (FB) record format
and the remaining attributes will be computed. If `src` is binary,
`dest` will have a Fixed Block (FB) record format with a record length
of …
=> Release v1.4.0 beta.2

changelogs/fragments/546-enable-zos_operator-func-test.yml, tests/dependencyfinder.py, tests/functional/modules/test_zos_operator_action_query_func.py
This pull request will re-enable the test_zos_operator_func.py based on the fact they have been tested locally with zoau 1.2.1 such that now the issue #379  is resolved in ZOAU. 
This issues also resolves #547 which fixes a bug in the dependencyfinder where subprocess would return a truncated relative path because the columns value was not large enough. 
=> Enable previously deprecated test cases for zos_operator and fix dependencyfinder

plugins/modules/zos_copy.py, tests/pytest.ini
Implements #408.
zos_copy
The module now keeps track of overwritten and new members when copying into a PDS/PDSE. When an error occurs during the copy operations, the `restore_backup` function restores overwritten members and erases new members, without reallocating the data set.
=> [Feature] [zos_copy] Restore members on module failure

plugins/module_utils/data_set.py, tests/functional/modules/test_zos_copy_func.py
Fixes #543.
zos_copy
This issue is probably caused by a bug in ZOAU where volumes with system symbols are not properly handled (the original data set reported in the issue was `SYS1.SAMPLIB`, which is located in a volume like that), so `dls` is unable to get the data set's information. This is a bugfix intended for v1.4.0, where we still won't be supporting ZOAU 1.2.x officially. In v1.5.0, the dependency on a newer ZOAU should make this bugfix unnecesary, as the bug in `dls` is already fixed there.
The bugfix is just a call to `LISTDS` through `IKJEFT01` when `dls` doesn't return the data set information.
=> [Bug] [zos_copy] Fix for data set type error

plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
Fixes an issue discovered by a client where `zos_copy` would try to backup the parent directory of the destination when copying a source directory without using a trailing slash. Now the module creates an emergency backup of the directory it'll replace, and not of the whole parent directory.
zos_copy
Related to #554. The bugfix for that issue unearthed this one.
=> [Bug] [zos_copy] Updated backup path used when copying directories

galaxy.yml
Minor update to ignore anything local that starts with venv with the added regular expression `*`.
Without this, the make file pulled in another local venv2 that increased our build size. 
=> Expand what is ingored for venv to all venv's

meta/runtime.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.9.txt
I locally validated that collection `ibm_zos_core` version 1.5.0-beta.1 have passed ansible-core ansible-test for versions 2.11, 2.12, 2.13, 2.14.
A false positive did come from pylint , i updated the version as well and still continued to get "Catching an exception which doesn't inherit from Exception" see [doc](https://pylint.pycqa.org/en/latest/user_guide/messages/error/catching-non-exception.html).
I reviewed the source in ZOAU that was being raised and it was correct. I think the issue is pylint can't find the ZOAU API which is on the managed node not the local machine. 
Notes taken during validation:
```
ddimatos:[ ~/git/github/ibm_zos_core ]make build
====================================================================
Building Ansible …
```
=> Ansible-core versions with updated ignore file pass

Makefile
Overrides the original behavior of the Makefile that always expected one venv called 'venv'. By reading an exported var VENV, the make file and be used to interact with any number of virtual environments expediting localized testing. 
For example I will pass in my own requirements.txt then instruct the Makefile which make file and directory to build it for.
```
export VENV=venv-2.11
make vsetup req=requirements-ac-2.11.12.txt
```
```
ls -la 
drwxr-xr-x  10 ddimatos  staff     320 Jan 18 20:56 venv-2.11
```
Now I can do this:
```
ddimatos:[ ~/git/github/ibm_zos_core ]export VENV=venv-2.11
ddimatos:[ ~/git/github/ibm_zos_core ]make sanity version=3.8
Running sanity test "action-plugin-docs"
Running sanity test "ansible-doc"
```
or switch between …
=> Update make file to read exported var VENV else default to 'venv'

changelogs/fragments/588-zos_copy-emergenxy-backup.yml, plugins/modules/zos_copy.py
Fixes #588 on v1.5.0 release. Same PR as #590 but based on release branch v1.5.0
zos_copy.
Removed the use of an emergency backup when Force=True. If a user wants a backup of the destination, the original backup code is still in the module and it's run when Force=False.
=> Bugfix/558/zos copy backup v.1.5.0

changelogs/fragments/601-copy-loadlib-member.yml, plugins/modules/zos_copy.py
Fixed error when a load lib member was copied to another load lib. Apparently error is found in stdout instead of err.
Fixes #601 
zos_copy
```paste below
```
=> Bugfix/601 copy lib member 1.5.0

changelogs/fragments/647-zos_data_set_record_format.yml, docs/source/modules/zos_data_set.rst, plugins/modules/zos_data_set.py, tests/conftest.py
This addresses issues #638 and #646 such that when the default value for record format FB was set it was was also set for VSAM and this would break VSAM data set creation. It did not make sense to not have a default so it was added back after going through the changes enforced by ansible 2.14. This code adds the correcting behavior.
```
BGYSC1402E Dynalloc ' 'Failure. Error Code: ' '0x9700, Information Code: '"0x00\\n
```
See git issue #646 for more detals
```paste below
```
=> Corrects zos_data_set default record format FB breaking VSAM

changelogs/fragments/648-zos_operator-examples.yml, plugins/modules/zos_operator.py
Fixes zos_operator module examples, fixes issue #390 
=> Update the module with the correct examples and descriptions

changelogs/fragments/728-zos_operator-example-updates.yml, docs/source/modules/zos_operator.rst, plugins/modules/zos_operator.py
Fixes #612 to correct the example commands in the doc.
=> zos_operator documentation escape example correction

changelogs/fragments/729-zos_operator-example-added.yml, docs/source/modules/zos_operator.rst, plugins/modules/zos_operator.py
Fixes #612 to add the `D SYMBOLS` command to the examples.
```paste below
```
=> Added additional `D SYMBOLS` example to  zos_operator documentation

changelogs/fragments/729-zos_operator-example-added.yml, docs/source/modules/zos_operator.rst, plugins/modules/zos_operator.py
Fixes #612 to add the `D SYMBOLS` command to the examples.
```paste below
```
=>  Added additional D SYMBOLS example to zos_operator documentation

changelogs/fragments/417-can-quotes-in-content-can-be-supported.yml, plugins/modules/zos_blockinfile.py, tests/functional/modules/test_zos_blockinfile_func.py
To verify dmod function support a block with double quotes for users to add a reference or commands that need it
Bugfix #417 can quotes in content be supported
Delete the case for delete the quotes in the block statement and add the function to keep the quotes in the final message for the user to know the quotes are keep as part of the block,
Add additional test case for double quotes included in the block space 
test_uss_block_insert_with_doublequotes
TEST_CONTENT_DOUBLEQUOTES 
Create function to keep the double quotes to json format and the get back for Ansible response format
quotedString_outputJson
=> zos_blockinfile , can quotes in content can be supported

changelogs/fragments/417-can-quotes-in-content-can-be-supported.yml, changelogs/fragments/619-Mode-set-for-files-is-applied-to-destination-directory.yml, plugins/module_utils/encode.py, plugins/modules/zos_blockinfile.py, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_blockinfile_func.py
Fixed bug #619  Mode set for files is applied to destination directory by change the logic of changing files
The new logic is one is not a folder so only a file the mode will change not everything to be copy by the module
=> zos_copy mode is applied to the destination directory, a deviation from the communtiy module behavior.

changelogs/fragments/358-zos-data-set-support-disposition-shr.yml, plugins/module_utils/data_set.py, plugins/modules/zos_data_set.py, tests/functional/modules/test_zos_data_set_func.py
leverages new ZOAU capability `mrm -f`to open a pdse in disp=shr mode and facilitate member delete while pdse is in use by another process.
Addresses issue #358 
=> zos_data_set - add force parameter to enable member delete via disp shr

changelogs/fragments/565-zos_tsocommand_maxrc.yml, changelogs/fragments/666-zos_tso_command_maxrc.yml, plugins/modules/zos_tso_command.py, tests/functional/modules/test_zos_tso_command_func.py
Added max_rc as a parameter to tso_command
This allows return codes > 0 to pass:
+ (changed becomes true, 
+ failed becomes false
+ original rc in origrc
+ rc set to 0
Includes a new test that lists databases (that are not on ec's) to force an rc=4
Ticket #565 
```paste below
```
Build passed:
=> Add max_rc support for module zos_tso_command

changelogs/fragments/725-zos_copy-encoding-bugs.yml, changelogs/fragments/732-zos_copy-encoding-bugs.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
Fixes for both #664 and #678, but now for release 1.4.1. The same code found in PR #725.
zos_copy
=> Fixes for #664 and #678 for 1.4.1

changelogs/fragments/739-zos_copy-volume-symbol-test.yml, tests/functional/modules/test_zos_copy_func.py
This adds a test for testing of special chars in a volume. This test cases verifies that zoau 1.2.2 has corrected the behavior hence we only pulled the test case forward from 1.4.0 and not the work around. 
Resolves  #738 
=> zos_copy forward port a test case for symbols on a volume

changelogs/fragments/746--Mode-set-for-files-is-applied-to-destination-directory.yml, plugins/modules/zos_copy.py
Mode set for files is applied to destination directory by change the logic of changing files
Fixed https://github.com/ansible-collections/ibm_zos_core/issues/619
Add logic if to verify the destiny folder to copy to only change mode to files not folder.
When the only and last file of the copy is a folder does not apply the change of mode with and if statement.
The PR in dev pass without test case, more than playbook results.
Add playbook
hosts : zvm
collections :
ibm.ibm_zos_core
gather_facts: no
vars:
ZOAU: "/zoau/v1.2.2"
PYZ: "/python2/usr/lpp/IBM/cyp/v3r2/pyz"
source: ./tests/
destt: /test/
environment: "{{ environment_vars }}"
tasks:
name: Delete al files inside folder dest
shell:
cmd: rm -r {{ destt }}
name: Create dest folder
shell:
cmd: mkdir {{ destt }} …
=> Solve problem 619 about set mode on dest file

plugins/module_utils/encode.py
There is a duplicated function in line 456 and line 499 `uss_tag_encoding`
- Trivial Pull Request
module_utils/encode.py
The linter somehow doesn't seem to complain about the fact that there are two functions with the same name.
```paste below
```
=> Remove duplicate function uss_tag_encoding from encode utils

plugins/module_utils/zoau_version_checker.py, tests/unit/test_zoau_version_checker_unit.py
NOTE - this PR is a copy of PR #796. This targets the 1.6.0 staging branch whereas the other incorrectly target the 1.6.0-beta.1 staging branch.
Updates the way zoau version checker parses output from `zoaversion`. Prior implementation grabbed the very last space-separated "word" but with newer ZOAU version, `zoaversion` started outputting additional buildinfo and the very last "word" was no longer the version info. New implementation starts parsing from the front.
Also adds unit tests with a long list of `zoaversion` output from various ZOAU versions. This list will need to be updated periodically as new versions of ZOAU are released to ensure the zoau version checker is still valid.
Fixes [GH Issue 783](https://github.com/ansible-collections/ibm_zos_core/issues/783)
- Bugfix Pull …
=> update zoau version checker and add unit testing

ac, changelogs/fragments/791-doc-zos_data_set-member-update.yml, changelogs/fragments/791-zos_data_set-update-vsam.yml, docs/source/modules/zos_data_set.rst, docs/source/modules/zos_job_query.rst, docs/source/modules/zos_job_submit.rst, meta/runtime.yml, plugins/module_utils/data_set.py, plugins/modules/zos_data_set.py, tests/functional/modules/test_zos_data_set_func.py, tests/sanity/ignore-2.16.txt
Given this change will drive over 700 tests it made sense to collapse all the related zos_data_set into one PR to avoid multiple regression pipelines.
1. Documentation: When a MEMBER is created, the format type of the member was not described, it should be clearly defined so that a user does not try to insert an executable into the data formatted member. Issue #631 
2. Bug: A random issue would occur on the pipeline leaving behind VSAM cluster components be it INDEX or DATA, originally this was thought to be a test case issue and a simple test fix but after reviewing I found it much more complex and took a better part of the week to address. To fix this I had to undo most of what was done in  PR [325](https://github.com/ansible-collections/ibm_zos_core/pull/325) for bugfix #140. Although …
=> Update zos_data_set member description created

changelogs/fragments/810_fix_binary_file_bypass.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
Fixes #807. Code introduced in 1.5.0 in `zos_copy` tried to convert the encoding of binary files, resulting in an error when the file was tagged as `binary` on z/OS or invalid bytes for UTF-8 were read.
zos_copy
Added a couple of test cases to validate the handling of binary files.
=> Bugfix for #807 - zos_copy ignores encoding for binary files

.ansible-lint, CHANGELOG.rst, README.md, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, changelogs/fragments/v1.6.0_summary.yml, docs/source/release_notes.rst, galaxy.yml, meta/ibm_zos_core_meta.yml, meta/runtime.yml
This PR does not resolve issue #733 but this PR helps bring #733 closer to completion. 
Version 1.6.0
=============
New Modules
-----------
- ``zos_volume_init`` - Can initialize volumes or minidisks on target z/OS systems which includes creating a volume label and an entry into the volume table of contents (VTOC).
Minor Changes
-------------
- ``zos_blockinfile`` - Adds an enhancement to allow double quotes within a block.
- ``zos_copy``
- Updates the behavior of the `mode` option so that permissions are applied to existing directories and contents.
- Adds an enhancement to option `restore_backup` to track modified members in a data set in the event of an error, restoring them to their previous state without reallocating the data set.
- ``zos_data_set`` - Adds a …
=> Release tasks v1.6.0

.github/ISSUE_TEMPLATE/enhancement_feature.issue.yml, docs/source/modules/zos_archive.rst, docs/source/modules/zos_unarchive.rst, plugins/action/zos_unarchive.py, plugins/modules/zos_archive.py, plugins/modules/zos_unarchive.py, tests/functional/modules/test_zos_archive_func.py, tests/functional/modules/test_zos_unarchive_func.py
New module development: zos_archive and zos_unarchive. I added both into the same branch for easy test since each complement the other. This module is able to archive/unarchive different USS formats :
- tar
- zip
- bz2
- gz
- pax
And some MVS data sets formats:
- xmit(RECEIVE operation for unpacking)
- terse
Gives different options to each format such as the ability of perform a restore using ADDRSSU or skip it.
Design decisions: 
- Added amaterse and adrdssu calls into mvs_cmd.
- Creation of an action plugin for zos_unarchive to transfer the data into the managed node before unarchiving.
zos_unarchive
```paste below
```
=> Module zos_unarchive & zos_archive

changelogs/fragments/880-Functional_tso_command_test_cases_currently_can_not_be_run_concurrently.yml, tests/functional/modules/test_zos_tso_command_func.py
The change substitute a set of test that depends of a sequential run and summarized in one large test with some of the options tested before and remove hardcoded verifications.
Fixes #880 
Take logic of 8 tests and validation of each one, that required a sequential run  to just one test in the right sequence.
`test_zos_tso_command_allocate_listing_delete`
=> Functional tso command test cases currently can not be run concurrently#880

changelogs/fragments/906-update-doc-generation.yml, docs/Makefile, docs/scripts/post-template.sh, docs/scripts/post-zos_apf.sh, docs/scripts/pre-template.sh, docs/source/modules/zos_apf.rst, docs/source/modules/zos_archive.rst, docs/source/modules/zos_data_set.rst, docs/source/modules/zos_job_output.rst, docs/source/modules/zos_job_query.rst, docs/source/modules/zos_job_submit.rst, docs/source/modules/zos_unarchive.rst, plugins/modules/zos_apf.py, plugins/modules/zos_archive.py
This improves the make file such that pre and post scripts are invoked to process some of the RST known to need additional editing. 
This issue will:
- update the make file
- new scripts
- correct `zos_copy`, `zos_job_submit`, `zos_archive` and` zos_apf` module doc
- generate new doc using the updated make file
- generate doc for modules that had updates that would normally be caught in the release process but doing so now. 
Addresses issue #905
=> Update make file doc generation with pre and post scripts for a subset of modules.

changelogs/fragments/918-zos-operator-response-come-back-truncate.yaml, tests/functional/modules/test_zos_operator_func.py
Add test case to validate the solution on of command response is full in the output.
Validate the fix #782 
Test case test_response_come_back_complete that validates the final line of the response contains HASP646
Required ZOAU 1.2.4
=> Add test case to validate response come back complete

changelogs/fragments/934-Remove-conditional-unnecessary.yml, tests/functional/modules/test_zos_blockinfile_func.py
Fix conditionals for next issues in runs of pipeline
The test is the one about backups and to ensure removes the dataset at the end, it was required the assignation of a dataset name with or without a member, one of the options of backup is None, the conditional it was for case None to ensures the delete of dataset but generate and error because variable not assigned of case None.
=> Remove conditional unnecessary

changelogs/fragments/964-modify-get_data_set_attributes-function.yml, plugins/modules/zos_copy.py
Honor incoming param values instead of overwriting in the case of is_binary=True
Functionally, there should be no changes (other than the case where `executable=True` and `is_binary=True` and the helper function was overwriting record format and record length set up for executable (recf=U, recl=0) with overriding behavior (recf=FB, recl=80). 
This fix does not modify any incoming values. 
Fixes #924 
=> modify get_data_set_attributes function

changelogs/fragments/965-enhance-archive-tests.yml, tests/functional/modules/test_zos_archive_func.py, tests/functional/modules/test_zos_unarchive_func.py
Enhance the zos_archive and zos_unarchive, original idea was to simplify test cases but added test_lines with the actual record length of the dataset and take into account RDW.
Fixes #897 
=> Enhance zos_archive and zos_unarchive test cases

changelogs/fragments/969-Simplify_loadlib_test_cases.yml, tests/functional/modules/test_zos_copy_func.py
Simplify test case for executable.
Fixes #958 
- Enhancement
Generate two functions that will works as helpers to ensure the creation of executables files to remove unnecessary an repetitive case for test case.
Generate two functions that will works as helpers to ensure the creation of executables files to remove unnecessary an repetitive case for test case, also by dividing the cases by test ensuring proper understanding and calls of functions.
=> Simplify loaldlib test cases

.github/ISSUE_TEMPLATE/bug_issue.yml
Since some users have picked wrong versions that are not yet available we agreed to change the bug options to only latest released and "to release", so I kept v1.8.0-beta.1 in case a user founds and issue in dev branch.
didn't write a changelog fragment entry because is not a change to the codebase or testing suite.
=> Modified versions in bug issue template to avoid users picking a non-existing version

changelogs/fragments/969-Simplify_loadlib_test_cases.yml, changelogs/fragments/980-zos-copy-disp-shr.yml, plugins/action/zos_copy.py, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
zos_copy does not support interactions with data sets that are already in use by other processes (DSP=SHR). With these changes using force flag now user can issue copies for these data sets.
Fixes #735 
zos_copy
=> Added latest to allow member copy when disp=shr

changelogs/fragments/920-bug-add-library-feature-documentation.yml, changelogs/fragments/920-zos-copy-add-library-choice.yml, docs/source/modules/zos_copy.rst, plugins/modules/zos_copy.py
Change to zos_copy:
Added LIBRARY type to dest_dataset/suboptions as a valid choice
Updated in file documentation to reflect the option
Fixes #920 
- Bugfix Pull Request (missing option)
- Docs Pull Request (added option)
zos_copy.py
=> Initial commit to add LIBRARY to choices and docs

plugins/modules/zos_copy.py
This fixes issue #836 which is only a doc change to describe how DBRMs can be supporting with `zos_copy`
=> Added DBRM doc to zos_copy module

.ansible-lint, CHANGELOG.rst, README.md, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, docs/source/modules/zos_gather_facts.rst, docs/source/release_notes.rst, galaxy.yml, meta/ibm_zos_core_meta.yml, meta/runtime.yml, plugins/action/zos_copy.py, plugins/modules/zos_apf.py, plugins/modules/zos_encode.py, plugins/modules/zos_gather_facts.py
This merges the meta data changes made in version 1.7.0 (`git cherry-pick  4726116`) for issue #888 
From this PR [here](https://github.com/ansible-collections/ibm_zos_core/commit/4726116eac771a3db633400b2a3fd932a5d652f3) 
We need to have these changes in our `dev` branch will be Q4 1.9.0-beta.1, the metadata changes and doc changes must travel be pushed upstream to `dev`.
* Galaxy 1.7 updates
* Update meta runtime to support ansible-core 2.14 or later
* Update ibm_zos_core_meta.yml with updated version
* Update readme to align to supported ansible versions and new urls
* Added additional sanity ignore files to the exclude list
* Added additional sanity ignore files to the exclude list for ansible-lint.
* Update copyright yrs for source files that were overlooked
* Remove requirements …
=> Staging v1.7.0 merge to main (#1019)

changelogs/fragments/1051-try-except-pass-zos_mvs_raw.yml, plugins/modules/zos_mvs_raw.py
Currently Bandit marks Try, Except, Pass as a warning, since is not a security issue but rather a behavior that might ignore wrong doings.
In this case, we know the code is only used to find a data set and catalog, this action can throw an exception if a data set name is not valid (not really bc we validate it) and if there is an error cataloging that data set. If there is an error cataloging we just forget about that data set assuming it doesn't exist and create a new cataloged one.
This PR does not change any behavior.
Added details of the code to changelog, since is a trivial change it will not be included in the release notes so no final user will see this.
Fixes #877 
zos_mvs_raw
```paste below
```
=> [Enabler] [zos_mvs_raw] Remove Try, Except, Pass from code

changelogs/fragments/1052-try-except-pass-dd-statement.yml, plugins/module_utils/dd_statement.py
Currently Bandit marks Try, Except, Pass as a warning, since is not a security issue but rather a behavior that might ignore wrong doings.
This change instead catches any data set deletion error and passes, but raises any other potential issue.
Added details of the code to changelog, since is a trivial change it will not be included in the release notes so no final user will see this.
Fixes #876 
module_utils/dd_statement.py used also by zos_mvs_raw.
```paste below
```
=> [Enabler] [module_utils/dd_statement.py] Changed try except pass to except specific DatasetDeleteError exception

changelogs/fragments/1049-xmit-temporary-data-sets.yml, plugins/modules/zos_unarchive.py
There is a method that cleans the environment when unpack action fails on remote with mvs commands, currently when remote_src is False temporary data set was not removed, changed that behavior to ensure it happens when mvs formats unpack fails.
Since this is a cleanup of temporary data set I thought about creating test cases, but it can fail in multiple steps, I do have a playbook which you can use to test the behavior but let me know If you think is necessary to create a test case for it.
THIS IS A BACKPORT FOR V1.8.0 AND THIS WAS MERGED TO DEV IN PR #1049. FIXES #1047 FOR V1.8.0
zos_unarchive
=> [v1.8.0][Backport] Clean temporary data sets created during XMIT unarchive operation

changelogs/fragments/1055-remove-subprocess-encode.yml, plugins/module_utils/encode.py, plugins/module_utils/system.py
Removed use of subprocess from system utils, since the only use of it could be replaced for AnsibleModule run_command method. Removing the use of subprocess from our workflow avoids us having to explain the need to open a subprocess and rather filter the command through ansible own dedicated method (AnsibleModule.run_command). That way we are reverting back from a change done 3 years ago, when it was decided to use our own implementation of subprocess instead of Ansible's, but looking at our modules, we actually use this AnsibleModule wrapper all around and can't think of a reason of why not using it here too.
Also, to avoid future implementations of system.run_command without a solid reason I commented the method's code.
I used a trivial tag as changelog to avoid displaying this to the …
=> Removed run command  use of subprocess from encode defaults infavor of using AnsibleModule run command

changelogs/fragments/1041-bug-zos-submit-job-honor-return-output-literally.yml, changelogs/fragments/1043-bug-title-zos_operator-is-passing-wrong-value-to-zoauopercmd.yml, plugins/module_utils/job.py, plugins/modules/zos_job_submit.py, plugins/modules/zos_operator.py, plugins/modules/zos_operator_action_query.py, tests/functional/modules/test_zos_operator_func.py
backport of 1041 and 1044 for 1.8.0 ga
Fixes 
#1041  : Option return_output when set to false continues to access job output in zos_submit_job
#1044 : zos operator is passing wrong value to zoauopercmd for delays
zos_submit_job
zos_data_set <= zos_operator and zos_operator_action_query
=> Cherry picked v1.8.0

changelogs/fragments/1060-remote_tmp_zos_script.yml, docs/source/modules/zos_script.rst, plugins/action/zos_script.py, plugins/modules/zos_script.py, tests/functional/modules/test_zos_script_func.py
Fixes #1024. Instead of implementing its own temp path, the module now takes advantage of Ansible's config.
zos_script
Removed the test case for `tmp_path` since now it belongs to the Ansible engine.
=> Enabler/1024/remote_tmp for zos_script

changelogs/fragments/1064-corruped-second-copy.yml, plugins/modules/zos_copy.py
=> [zos_copy] Files corrupted after second copy

changelogs/fragments/1060-remote_tmp_zos_script.yml, docs/source/modules/zos_script.rst, plugins/action/zos_script.py, plugins/modules/zos_script.py, tests/functional/modules/test_zos_script_func.py
Backport of #1060 for v1.8.0. Fixes #1024.
zos_script
=> [v1.8.0] [Backport] [zos_script] remote_tmp for zos_script

changelogs/fragments/1065-rexx-exec-tso_command.yml, docs/source/modules/zos_tso_command.rst, plugins/modules/zos_tso_command.py
=> [Documentation] [zos_tso_command] Add REXX exec example

changelogs/fragments/1067-mvs_to_non_existent_mvs_copy_verify_destination_attrs_match.yml, plugins/module_utils/data_set.py, plugins/modules/zos_copy.py
The copy of an executable and aliases in a dataset to a creation to another dataset not in existence modify size.
Fixes #1022 
Remove the function of ensure_present and modify the function of allocate model data set to include the correct one for executables.
Remove the ensure_present function by calculating the size and now using function of allocate_model_data_set to include a case about executable using:
`if executable:
alloc_cmd = """{0} -
RECFM(U) -
DSNTYPE(LIBRARY)""".format(alloc_cmd)`
[Pipeline](https://ibm.box.com/s/lyudfq6vwdm2i822bm7fva90sf6xxcnc)
=> [v1.8.0] [Backport] [zos_copy] mvs to non existent mvs copy verify destination attrs match

changelogs/fragments/1066-Mvs_to_non_existent_mvs_copy_destination_attrs_match_up.yml, plugins/module_utils/data_set.py, plugins/modules/zos_copy.py
The copy of an executable and aliases in a dataset to a creation to another dataset not in existence modify size.
Fixes #1022 
Remove the function of ensure_present and modify the function of allocate model data set to include the correct one for executables.
Remove the ensure_present function by calculating the size and now using function of allocate_model_data_set to include a case about executable using:
`if executable:
alloc_cmd = """{0} -
RECFM(U) -
DSNTYPE(LIBRARY)""".format(alloc_cmd)`
Pipeline [link](https://ibm.box.com/s/8pcr3xaroylum25fw70kzynlj7gle0pi)
=> Mvs to non existent mvs copy destination attrs match up

changelogs/fragments/1079-zos-copy-local-executable.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
This fixes #1080 for branch v1.8.0, essentially this removes any encoding for when a local file is sent to remote, also, when dest_type is not available i.e. dest doesn't not already exists now we set the dest_ds_type = 'PDSE' when executable is selected and we know dest is not USS (validation performed on src checking for '/'), which then gets changed to "LIBRARY", note that I also added a check when copying to PDS/PDSE, that is because when the a local file is copied to remote dest_ds_type gets changed to "LIBRARY" however this doesn't occur when copying an executable from the remote (I believe the data set type we get is PDSE) and that needs to be further investigated in #1080 for v1.9.0 fix.
This current version does solve the issue and does not break anything that we are testing for, …
=> [zos_copy] fix for executables copied from local fail with iconv error

changelogs/fragments/1077-modify-uss-extraction.yml, plugins/modules/zos_unarchive.py
Replaced extractable call to a custom extract_all to remove bandit warning, members are filtered before using sanitize_members so this doesn't change any behavior.
Fixes #1075 
zos_unarchive
=> Remove tarfile.exctractall and zipfile.extractall in favor of individual member extraction for sanity

plugins/modules/zos_mvs_raw.py
Fixes 3 sanity issues added in the last zos_mvs_raw PR :
---------ERROR: ansible-test detected errors
ERROR: Found 3 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/zos_mvs_raw.py:1242:79: W291: trailing whitespace
ERROR: plugins/modules/zos_mvs_raw.py:3188:161: E501: line too long (163 > 160 characters)
ERROR: plugins/modules/zos_mvs_raw.py:3193:161: E501: line too long (171 > 160 characters)
Ans Test ==============================================================================
zos_mvs_raw
=> Fixed sanity issues with zos_mvs_raw

changelogs/fragments/1042-missing-zoau-imports.yml, plugins/module_utils/import_handler.py, plugins/module_utils/job.py, plugins/modules/zos_job_query.py, plugins/modules/zos_operator.py
Proposal for a solution for #837.
- zos_operator
- zos_job_query
- module_utils/job.py
To bubble up import errors from ZOAU, we'll still use the idea behind `MissingZOAUImport` but change around a few things to avoid losing important context when an import fails. For now it's just for zos_operator and zos_job_query/job.py, to showcase the two types of changes we'll need to do:
- Changes in module_utils where we always import at a module level instead of individual functions, and making sure modules use `to_text` to properly render the exception in the return JSON.
- Changes in modules where we do a check early on to catch import failures.
=> [v1.9.0] Bugfix/837/missing ZOAU imports

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/1041-bug-zos-submit-job-honor-return-output-literally.yml, changelogs/fragments/1043-bug-title-zos_operator-is-passing-wrong-value-to-zoauopercmd.yml, changelogs/fragments/1049-xmit-temporary-data-sets.yml, changelogs/fragments/1060-remote_tmp_zos_script.yml, changelogs/fragments/1067-mvs_to_non_existent_mvs_copy_verify_destination_attrs_match.yml, changelogs/fragments/1069-corrupted-second-copy.yml, changelogs/fragments/1072-rexx-exec-tso_command.yml, changelogs/fragments/1079-zos-copy-local-executable.yml, changelogs/fragments/1089-update-managed_node_doc.yml, docs/source/modules/zos_copy.rst, docs/source/modules/zos_job_submit.rst, docs/source/modules/zos_script.rst, docs/source/release_notes.rst, docs/source/requirements-single.rst, galaxy.yml, meta/ibm_zos_core_meta.yml, plugins/module_utils/data_set.py, plugins/module_utils/encode.py, plugins/module_utils/job.py, plugins/module_utils/mvs_cmd.py, plugins/module_utils/template.py, plugins/module_utils/zoau_version_checker.py, plugins/modules/zos_blockinfile.py, plugins/modules/zos_job_submit.py, plugins/modules/zos_operator.py, plugins/modules/zos_operator_action_query.py, plugins/modules/zos_tso_command.py
Part of the release process (#982) where we merge release tasks into the staging branch.
- Release Pull Request
=> Merge staging-v1.8.0-tasks into staging-v1.8.0

changelogs/fragments/1091-Update_undocumented_argument_and_import_exception.yml, plugins/action/zos_job_submit.py, plugins/modules/zos_job_submit.py, tests/functional/modules/test_zos_job_submit_func.py, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
Update temp_path and how to import exceptions.
Fiexes #997 #998 #999 
- Sanity Issue Pull Request
Remove tmp path from options and only work with source as name of tmp file, because it was undocumented argument for ansible and could be any name, also only in case is local make the tmp file, so didn't expect a dataset or file with the same name on the system. Also make a implementation of imports of exceptions by using new implementation to avoid losing context when an import fails.
Pipeline Without Zos_copy
Pipeline with zos_copy
=> [Enabler][Zos Job Submit]Update undocumented argument and import exception

changelogs/fragments/1078-short_job_name_sends_back_a_value_error.yaml, plugins/module_utils/better_arg_parser.py, plugins/modules/zos_job_output.py, plugins/modules/zos_job_query.py, tests/functional/modules/test_zos_job_output_func.py, tests/functional/modules/test_zos_job_query_func.py
Validate identifiers of jobs with better args parser and add test cases for validate the use of wildcards on short names.
Fixes #899 and validates #900
job_identifier as type in better arg parser
The new regex to validate job identifier `(^[a-zA-Z$#@%}]{1}[0-9a-zA-Z$#@%*]{2,7})|(^['\*']{1})`
And add to test cases to validate short jobs ids one with wildcard and one without.
[Here](https://ibm.box.com/s/9d4qd4fyico0pme3ab798gfhahme5u51)
=> [Bugfix][v1.9.0]short job name sends back a value error with a full stack trace as the msg

changelogs/fragments/1163-Refactor_calls_to_use_new_alias_and_execute_options.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
Refactor call of dataset._copy module to avoid dictionaries and change for options for executable and aliases.
Fixes #944 
- Enable Pull Request
Change the 3 calls of dataset.copy from option -IX to aliases=True/False and executable=True/False
(https://ibm.box.com/s/yqfis1sgb2e38moo2knx52go0x86oo2n)
=> [Enabler][zos_copy]Refactor calls to use new alias and execute options

changelogs/fragments/1176-copy-members.yml, plugins/action/zos_job_submit.py, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
Improved the performance of copying a PDS/PDSE with multiple members into another PDS/PDSE by providing the complete list of members to copy to datasets._copy zoau call.
This is some performance numbers comparing current dev copy as "old copy" and proposed solution as "new copy"
Testing copy with 30 members
old copy 474.17s, 339.17s, 310.62s, 607.13s
new copy 35.75s, 55.13s, 45.11, 51.61s
Testing copy with 100 members
old copy 1275.75s (21 mins), 1400.44s(23 mins)
new copy 47.15s, 115.71s
Also corrected a couple of false positives in the test cases section, one was trying to copy an empty PDS into another and was a false positive in the module code. Another, was always creating a PDSE regardless of the type described in the test.
zos_copy
=> [v1.9.0] [zos_copy] Enhancement/764/copy members

changelogs/fragments/1195-Add_prefer_volumes_user.yml, tests/conftest.py, tests/helpers/volumes.py
Add the option to add variable volumes as a list in test config to help avoid some volumes that fail.
Add read test_config to add prefer volumes
Use as fixture to call a list of volumes now read also user preference.
=> [Conftest]Add_prefer_volumes_user

changelogs/fragments/1184-remove-zos-fetch-dep-from-zos-copy.yml, tests/functional/modules/test_zos_copy_func.py
Fixes #1147.
- zos_copy (tests)
One of the loadlib tests had a call to zos_fetch, so our dependency finder dictated that every time zos_fetch got updated, we had to run all tests for zos_copy, which takes forever.
This change replaces that call to instead use `scp` to transfer loadlibs to the local filesystem.
=> [Enabler] [zos_copy] Remove zos_fetch call in loadlib test

changelogs/fragments/1189-migrate-module_utils-encode.yml, plugins/module_utils/encode.py
Migrated module_utils/encode.py
Fixes #1120 
```paste below
```
=> [v1.10.0] [module_utils/encode.py] Implement ZOAU 1.3 migration changes into module_utils/encode.py

changelogs/fragments/1196-zoau-migration-zos_gather_facts.yml, plugins/modules/zos_gather_facts.py, tests/functional/modules/test_zos_gather_facts_func.py, tests/unit/test_zos_gather_facts.py
Update module to leverage zoau python api for zinfo.
Update test cases accordingly.
Fixes #1109 
Fixes #1126
The biggest change made here was leveraging the python api available for zinfo rather than constructing and calling a shell command. Much of the validation was repurposed/reused, so the code looks fairly similar.
The minumum ZOAU version has been raised to 1.3.0 since older versions will now break with these newer changes (the python api for zinfo available in prior versions of zoau has changed).
The only error the zinfo python api raises is a ValueError, so the logic handling the BGYSC520xx errors is removed.
=> [v1.10.0] [zos_gather_facts] ZOAU 1.3 migration - zos_gather_facts

changelogs/fragments/1200-zos_backup_restore-sanity-issues.yml, plugins/modules/zos_backup_restore.py, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
Added the documented choices for `space_primary` into the module_args later used in argument spec, this change does not affect functionality.
Fixes #1197 
zos_backup_restore
=> [v1.10.0] [zos_backup_restore]Added choices for space type

changelogs/fragments/1217-validate-job-query.yml, tests/functional/modules/test_zos_job_query_func.py
As part of ZOAU 1.3 migration tasks I validated that zos_job_query works correctly, but in `zos_job_submit` wait option was removed so I removed it from the test cases and set a maximum wait time of 10 sec. 
Fixes #1141 
zos_job_query
=> [v1.10.0][zos_job_query] Removed wait argument from test cases

ac, scripts/requirements-2.12.env, scripts/requirements-2.13.env, scripts/requirements-2.14.env, scripts/requirements-2.15.env, scripts/requirements-2.16.env, scripts/requirements-2.9.env, scripts/venv.sh
Addresses #1223 
- The ac tool had a typo that was causing copy and paste errors when using the help function, passsword.
- The ac tool did not support in the requirements.env the idea of a conditional operator for python, eg, "==" so "==:python:3.9" or ">:python:3.9" which is helpful when you want to use the latest version of python on a host that is permitted for the version of ansible. Before this, with the the operator, the latest version of python is selected, eg python 13 and it might not be supported by the venv being created for an ansible version.
- The ac tool also when no password is supplied would echo out the env vars to use, but to aid users now a dummy stub configuration is included with the venv creation that can be later edited easing a user from having to figure out the …
=> Enabler updates the AC tool with operator support for python and changes python search order.

changelogs/fragments/1228-zos_find-remove-zos_lineinfile_dep.yml, tests/functional/modules/test_zos_find_func.py
Removed zos_lineinfile dependency to be able to test zos_find with ZOAU 1.3 ahead of time.
Fixes #1142 
zos_find
=> [v1.10.0][zos_find] Removed lineinfile dependency and test with ZOAU 1.3

changelogs/fragments/1247-volser-parsing-leading-dash-bugfix, changelogs/fragments/1247-volser-parsing-leading-dash-bugfix.yml, plugins/module_utils/data_set.py
backports a fix for a minor parsing issue in the `data_set_cataloged_volume_list()` function where the contents of LISTCAT are parsed for volume serials. The issue was the volser str was assumed to be exactly 6 chars, and if it wasn't, the requisite number of `-`s where prepended. 
- See more details outlined in the bugfix - #1240
- Fixes #1245 
=> [v1.9.0] [backport] [Bug] [module_util/data_set] Remove leading '-' chars from parsed volume serial strings

changelogs/fragments/1236-bugfix-zos_apf-return-list.yml, plugins/modules/zos_apf.py
Add a concatenation of data sets when the list option is selected instead of just returning the last data set.
There is no need to forward port this into v1.10.0, since it is already fixed there.
Fixes #1235 
zos_apf
=> [v1.9.0][zos_apf] Fix list operation only returning one data set

changelogs/fragments/1257-zoau-import-zos_apf.yml, plugins/modules/zos_apf.py, plugins/modules/zos_backup_restore.py
During ZOAU 1.3 migration tasks we are also updating the way zoau imports are done. This was skipped during the ZOAU 1.3 migration for zos_apf.
This is part of #1087 , and based on my analysis all other ZOAU imports should be fixed in ZOAU 1.3 Migration PRs.
zos_apf
=> [zos_apf] Standardize ZOAU Imports

changelogs/fragments/1202-doc-gen-script-portability.yml, docs/scripts/post-zos_apf.sh, docs/scripts/pre-template.sh
Trivial change to sed "-i" in place option which ensures compatibility between MacOS and  GNU versions of sed command. This should help us use the tool via a linux based automated instance (most probably Jenkins vm).
doc scripts
Doc builds run successfully and do not introduce sanity issues 
```
(AC2.14PY3.9) fernandoflores@Fernandos-MacBook-Pro docs % make clean
====================================================================
Running Target clean
====================================================================
Deleting directory '/Users/fernandoflores/Documents/IBM/Repos/ibm_zos_core/docs/build'.
Deleting directory '/Users/fernandoflores/Documents/IBM/Repos/ibm_zos_core/docs/source/modules'.
Completed cleanup, run 'make module-doc' or 'make role-doc'. …
```
=> [Enhancement] [Doc scripts] Modifed doc scripts to ensure compatibility between MacOS and GNU sed commands

changelogs/fragments/1261-job-submit-non-utf8-chars.yml, plugins/module_utils/job.py, tests/functional/modules/test_zos_job_query_func.py, tests/functional/modules/test_zos_job_submit_func.py
Fixes #1160.
Fixes #677.
Fixes #972.
Fixes #1260.
- zos_job_submit
See issue #1255 too.
=> [v1.10.0] [zos_job_submit] Handling of non-UTF8 chars in job output

plugins/modules/zos_archive.py, plugins/modules/zos_unarchive.py
Replaced the use of `path` to `src` in zos_archive and zos_unarchive documentation.
Fixes #1267 
zos_archive
zos_unarchive
=> [v1.9.0] [Documentation] Replaced path to src in zos_archive and zos_unarchive documentation

changelogs/fragments/1246-bugfix-zos_job_submit-typrun.yml, plugins/module_utils/job.py, plugins/modules/zos_job_submit.py, tests/functional/modules/test_zos_job_submit_func.py
Address issues:
-  #1246 
- #1278 
When JCL is submitted with a job card indicating the job should only be validated with TYPRUN=SCAN the message that is returned is in this format:
> "msg":"The JCL submitted with job id JOB00406 but there was an error, please review the error for further details: The job return code was not available in the job log, please review the job log and error ? ?."
This PR adds support to such that typrun=scan does not trigger a job submission failure with updated `ret_code` values:
```
"ret_code": {
"code": null,
"msg": "TYPRUN=SCAN",
"msg_code": null,
"msg_txt": "The job JOB00283 was run with special job processing TYPRUN=SCAN. This will result in no completion, return code or job steps and changed will be false.",
"steps": []
},
```
Collaboration
IBM z/OS …
=> [v1.9.0] Collaboration 1246 to add typrun support for zos_job_submit

changelogs/fragments/1294-doc-zos_ping-scp.yml, changelogs/fragments/1295-doc-zos_ping-scp.yml, docs/source/modules/zos_ping.rst, plugins/modules/zos_ping.py, plugins/modules/zos_ping.rexx
Addresses issue #1281 and also updates the REXX to check for Python 3.10 or later since 1.9.0 will support only 3.10 or later. 
zos_ping
=> [v1.10.0-beta.1][port forward] Documentation to update zos_ping about the deprecated scp in OpenSSH 9 or later.

changelogs/fragments/1292-doc-zos_tso_command-example.yml, docs/source/modules/zos_tso_command.rst, plugins/modules/zos_tso_command.py
SUMMARY
Addresses issue https://github.com/ansible-collections/ibm_zos_core/issues/777 which is only to add a chained TSO command example.
Fixes #777 
ISSUE TYPE
Docs Pull Request
COMPONENT NAME
=> [v1.10.0-beta.1][port forward] Add chained command example to zos_tso_command

changelogs/fragments/1261-job-submit-non-utf8-chars.yml, changelogs/fragments/1288-job-submit-non-utf8-chars.yml, plugins/module_utils/job.py, tests/functional/modules/test_zos_job_query_func.py, tests/functional/modules/test_zos_job_submit_func.py
Fixes #1255.
Backports to v1.9.0 the fix from #1261.
- zos_job_submit
- module_utils/job.py
=> [v1.9.0] [Backport] [zos_job_submit] Handling of non-UTF-8 chars

changelogs/fragments/1298-Remove_local_charset_from_zos_fetch.yml, plugins/action/zos_fetch.py, plugins/modules/zos_fetch.py, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
Fix sanity issue about local charset by pass the value in the encoding parameter
Fixes #995 and fixes #996
Add a value of the to parameter of the parameter encoding to get the value for the controller machine.
=> [Enabler][995 996]Remove_local_charset_from_zos_fetch

plugins/module_utils/job.py, tests/functional/modules/test_zos_job_submit_func.py
This a correction to the code merged in #1261.
- zos_job_submit
- module_utils/job.py
ZOAU v1.3.0 still has problems handling control characters in a job's output (NL, CR, LF), so I added the handling of `JSONDecodeError` when reading output. Not adding a changelog fragment for now since this is related to work already merged.
=> [v1.10.0] [Bugfix] [zos_job_submit] Fix non-printable chars handling and testing in jobs

tests/functional/modules/test_zos_data_set_func.py
Some of the tests in test_zos_data_set_func.py were committing, then deleting non-existant file at the start of the test.  This was causing erratic behavior on some EC's.
This ticket was to reinstate those tests, and make sure they now work correctly.
Issue was 1193
unit test: test_zos_data_set_func.py first three tests
=> Pulled dev to un-comment data_set_func.py testing of committing non-existant files.

.github/ISSUE_TEMPLATE/bug_issue.yml
We've been lately relying on manual addition of "Needs Triage" label for community raised issues, so better to have it automatically added when a bug is reported.
```paste below
```
=> Automatically add "Needs Triage" label on bug creation template

.github/workflows/ac-bandit.yml
Added new github action that will run bandit upon a new pull request with base branch dev or any branch that starts with staging. By default, it will run on three triggers:
open
synchronize (every time the branch, with its PR in draft mode or ready for review gets a new push into remote).
reopen
You can see this Github Action in the following PR https://github.com/fernandofloresg/ibm_zos_core/pull/18
And look at the run details here https://github.com/fernandofloresg/ibm_zos_core/actions/runs/8363170326/job/22895488508?pr=18
It averages 26s of execution time
And looking at billable details we get 0s,
ac-bandit
```paste below
```
=> Create bandit github action using the ac command

.github/workflows/ac-ansible-test-sanity.yml, .github/workflows/ac-bandit.yml, .github/workflows/ac-galaxy-importer.yml, .github/workflows/ac_changelog.yml, plugins/modules/zos_apf.py
Updated the Github Action in the repository so that when PRs are in draft mode no action will be run, saving us some execution time.
Also updated the paths for when to run bandit and when to run the galaxy importer, basically bandit should only be executed when something under `plugins` changed, and galaxy importer when something that is included in the release tar is changed.
```paste below
```
=> Updated actions to only run when PR is not draft

changelogs/fragments/1355-update-docstring-zos_lineinfile.yml, plugins/modules/zos_lineinfile.py
Update docstrings on zos_lineinfile to the numpy standard
zos_lineinfile.py
```paste below
```
=> [Documentation][zos_lineinfile] Add and standarize docstrings on modules/zos_lineinfile.py

changelogs/fragments/1391-update-docstring-zos_volume_init.yml, changelogs/fragments/1392-update-docstring-zos_volume_init.yml, plugins/modules/zos_volume_init.py
Update docstrings on zos_volume_init to the numpy standard
zos_volume_init.py
```paste below
```
=> [Documentation][zos_volume_init] Add and standarize docstrings on modules/zos_volume_init.py

changelogs/fragments/1392-update-docstring-zos_apf.yml, changelogs/fragments/1393-update-docstring-zos_apf.yml, plugins/modules/zos_apf.py
Update docstrings on zos_apf to the numpy standard
zos_apf.py
```paste below
```
=> [Documentation][zos_apf] Add and standarize docstrings on modules/zos_apf.py

changelogs/fragments/1490-fix-gds-resolve.yml, changelogs/fragments/1496-fix-gds-resolve.yml, plugins/module_utils/data_set.py
Fix resolve GDS function to return a string with the gds name instead of zoau dataset object, this is the original design but was overlooked previously.
module_utils/data_set.py
=> [Enabler] Fix resolve GDS function to return a string with the gds name instead of zoau dataset object

changelogs/fragments/1507-zos_operator-docs.yml, plugins/modules/zos_operator.py
Updated doc entry with escaping instructions when using special characters.
Fixes #1471 
zos_operator
```paste below
```
=> [Documentation] Inform users the need to escape commands with special characters

changelogs/fragments/1338-update-docstring-zoau_version_checker.yml, plugins/module_utils/zoau_version_checker.py
Update docstrings on zoau_version_checker to the numpy standard
zoau_version_checker.py
```paste below
```
=> [Documentation][zoau_version_checker] Standarize docstrings on module_utils/zoau_version_checker.py

changelogs/fragments/1342-update-docstring-zos_backup_restore.yml, plugins/modules/zos_backup_restore.py
Update docstrings on zos_backup_restore to the numpy standard
zos_backup_restore.py
```paste below
```
=> [Documentation][zos_backup_restore] Standarize doc-strings on modules/zos_backup_restore.py

changelogs/fragments/1541-output_mvs_raw_gds_positive_was_false_positive.yml, plugins/modules/zos_mvs_raw.py, tests/functional/modules/test_zos_mvs_raw_func.py
First solution of adding gds name into the module generate a false positive using positive relative name.
Create the dataset if the name is a positive relative name.
First iteration did not generate a new gds, only was syntactically correct for the system.
=> [Bugfix][1377]output_mvs_raw_gds_positive_was_false_positive

changelogs/fragments/1543-mvs_raw_fix_verbose_and_first_character.yml, plugins/module_utils/dd_statement.py, plugins/module_utils/zos_mvs_raw.py
The dd_output by default use configuration of control that's why the first character was ignore, change now allows to be a regular dataset.
Fixes #1520 
new output
```
ok: [zvm] => {
"output": {
"backups": [],
"changed": true,
"dd_names": [
{
"byte_count": 5,
"content": [
"abcd",
""
],
"dd_name": "stdout",
"name": "OMVSADM.P6777740.T0791028.C0000000",
"record_count": 2
}
],
"failed": false,
"ret_code": {
"code": 0
},
"stdout": "BGYSC0307I Program: <bpxbatch> Arguments: <SH echo abcd>\nBGYSC0308I DDNames:\nBGYSC0312I   STDOUT=OMVSADM.P6777740.T0791028.C0000000\nBGYSC0303I Dataset allocation succeeded for STDOUT=OMVSADM.P6777740.T0791028.C0000000\nBGYSC0328I OS Load program BPXBATCH\nBGYSC0320I Addressing mode: AMODE31\nBGYSC0327I Attach Exit code: 0 from …
```
=> [bugfix][1520]mvs_raw_fix_verbose_and_first_character

changelogs/fragments/1549-zos_copy-opercmd.yml, plugins/modules/zos_copy.py
`zos_copy` was issuing an opercmd to see if the destination data set is locked even if it does not exist. Fix only issues the command if destination exists.
This is the fix meant for 1.9.2 release, did not add a test case for this scenario since automating a test to validate the command was not issued would take me some time, basically that would need to check the syslog to make sure the command was not issued for that specific data set name, I can add it if requested.
Fixes #1544 
zos_copy
```paste below
```
=> [v1.9.2][Bugfix] [zos_copy] Only issue opercmd to check for a locked data set if dest exists

changelogs/fragments/1570-compute-member-name-zos_copy.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
Fixes #774.
zos_copy
The module now computes the destination member name when the user only specifies the PDS/E dataset in `dest`, fixing the regression reported in #774.
=> [Bugfix] [zos_copy] Copy from file to member when dest is just PDS/E name 

changelogs/fragments/1565-remove-deprecated-pipes-library.yml, plugins/module_utils/backup.py, plugins/module_utils/copy.py, plugins/module_utils/encode.py, plugins/modules/zos_apf.py, plugins/modules/zos_find.py, plugins/modules/zos_mvs_raw.py, tests/functional/modules/test_module_security.py, tests/functional/modules/test_zos_apf_func.py, tests/functional/modules/test_zos_data_set_func.py
Fixes #1327.
- module_utils/backup.py
- module_utils/copy.py
- module_utils/encode.py
- zos_find
- zos_mvs_raw
- tests for zos_data_set
Not only does it remove the use of `pipes` in zos_data_set tests, but it also removes the use throughout the entire collection.
=> [Enabler] [Various modules] Remove use of deprecated pipes library

changelogs/fragments/1512-bugfix-zos_job_submit-error-type.yml, plugins/module_utils/job.py, plugins/modules/zos_job_submit.py
When a unicode or json decode error occur in a module its difficult to diagnose which occurred as each has a different solution. This will share the error type so development can better handle the diagnosis. 
#1512 
Note: there is no direct way to test this code because ZOAU has fixed the JSON decode and Unicode error thus we can not mock JCL to create a unicode or json error so I did locally mock some of these errors and caught the exception to ensure the code is working as planned. See issue #1512 attachment for more details on localized testing, the result of that testing showed the types were captured. 
> /tmp $: python3 json-test.py
> Non-printable UTF-8 characters were present in this output, a JSONDecodeError error has occurred.Please access the content from the job log.
> …
=> Update code to share exception types UnicodeDecodeError, JSONDecodeError, TypeError, KeyError

plugins/module_utils/backup.py, plugins/modules/zos_apf.py
Fixes a bug where the backup function would use outdated utilities to get the type of a dataset and fail when the name has a `$` in its name.
zos_apf
=> [Bugfix] [v1.11.0 beta.1] [zos_apf] Backup when using special symbols

changelogs/fragments/1640-quick-fix-ansible-core:2.17-verbosity-issue, plugins/action/zos_copy.py, plugins/action/zos_fetch.py, plugins/modules/zos_copy.py, plugins/modules/zos_fetch.py
Primarily affects modules:
- zos_copy
- zos_fetch
- zos_script
possibly affects:
- zos_archive/zos_unarchive
- zos_encode
ansible-core:2.17 changed the way the SFTP command is constructed, which resulted in SFTP output getting written to stderr, which triggers module failure,
An existing option, ignore_sftp_error, alleviates the issue. This PR merely changes the default value so that the module option is set to True by default.
- Fixes #1574 
Beyond passing regression based on dependencyfinder to ensure no previous functionality has been lost, as is standard, I've elected to run the pipelines using ansible-core:2.17 with "verbose" mode enabled against the standard dev branch and then again against this branch to prove that "verbose" mode was indeed broken and has …
=> Fix modules failing with verbosity with ansible-core:2.17

changelogs/fragments/1647-doc-backup-restore-racf-class.yml, docs/source/modules/zos_backup_restore.rst, plugins/modules/zos_backup_restore.py, tests/functional/modules/test_zos_backup_restore.py
Addresses issue #1540 
Adds documentation explaining the RACF class requirement for use with the modules restore option. 
```
notes:
- It is the playbook author or user's responsibility to ensure they have
appropriate authority to the RACF FACILITY resource class. A user is
described as the remote user, configured to run either the playbook or
playbook tasks, who can also obtain escalated privileges to execute as
root or another user.
- When using this module, if the RACF FACILITY class
profile B(STGADMIN.ADR.DUMP.TOLERATE.ENQF) is active, you must
have READ access authority to use the module option I(recover=true).
If the RACF FACILITY class checking is not set up, any user can use
the module option without access to the class.
- If your system uses a different security product, consult …
```
=> Update module with RACF authority doc

changelogs/fragments/1641-case-sensitivity-zos_operator.yml, docs/source/modules/zos_operator.rst, plugins/modules/zos_operator.py, tests/functional/modules/test_zos_operator_func.py
Fixes #1155.
zos_operator
Added a new option to the module, called `case_sensitive`, which is a boolean telling the module that the command is case sensitive and therefore not change the casing. Can change the name of the option, though.
=> [Enhancement] [zos_operator] Case sensitivity in zos_operator commands

changelogs/fragments/1689-add-non-utf8-testcase.yml, tests/functional/modules/test_zos_job_submit_func.py
This issue #1626 updates the test case to include testing of all non-printable utf8 characters. The test prints out all 255 chars in range and returns them, if any were to cause an issue the zoau dependency would have failed.
=> Add non-utf8 printables test case full coverage.

changelogs/fragments/1684-Add_validation_for_marker_begin_end.yml, plugins/modules/zos_blockinfile.py, tests/functional/modules/test_zos_blockinfile_func.py
Add documentation, test case and validation for user
Fixes #1678 
Add validation
=> [bugfix][1678]Add validation for maker begin end

CHANGELOG.rst, README.md, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, changelogs/fragments/v1.11.0-beta.1_summary.yml, docs/source/modules/zos_blockinfile.rst, docs/source/modules/zos_lineinfile.rst, docs/source/modules/zos_unarchive.rst, docs/source/release_notes.rst, docs/source/resources/releases_maintenance.rst, galaxy.yml, meta/ibm_zos_core_meta.yml, plugins/modules/zos_blockinfile.py, plugins/modules/zos_lineinfile.py, plugins/modules/zos_unarchive.py, tests/functional/modules/test_zos_encode_func.py
This is the last remaining task from the release task #1621 where I have cherry picked the the commit tagged into main so that I can merge those changes back into `dev`. 
* Fixed zos_copy
* Fixed encode test case
* update version and remove author
* Python is EOS 9-30, updated meta
* Update README with new links and cleanup
* Update GA dates
* Update module docs with auto generations
* Add changelog summary
* Changelog updates
* remove stale changelog files
* update galaxy exclusions
* update release notes for 1.11.0
* Remove unused imports from action plugin
* Corrections for flake8
* Updated example to not escape the paren
* Update module doc to correct use of monospace
* Corretions to release notes
* Corrections
=> Staging v1.11.0 (#1726)

changelogs/fragments/1698-multiple-args-zos_script.yml, plugins/action/zos_script.py, tests/functional/modules/test_zos_script_func.py
=> [Bugfix] [zos_script] Fix missing args when splitting command

changelogs/fragments/1746-deploy-forget-zos_job_submit.yml, plugins/modules/zos_job_submit.py, tests/functional/modules/test_zos_job_submit_func.py
Add deploy and forget capability to zos_job_submit. When `wait_time_s` is equal to 0, the module will only submit the job and not wait to pick additional details like job name, ret_code and so on.
We will still return the values in the result dictionary, for that we create an empty schema to make sure we return those values as empty when we don't explicitly modify them.
Created a new test case that calls the module with `wait_time_s` as 0 (this would previously fail) and asserts that we the schema is in place.
Also modified a few things that changed when ZOAU implemented the TYPRUN=SCAN enhancement, however, they set NOEXEC status for both TYPRUN=SCAN and TYPRUN=COPY. So had to change the test case and add the entry into the docs.
Left some comments in the test case for TYPRUN that are …
=> [v1.13.0][Enhancement] Add deploy and forget capability to zos_job_submit

changelogs/fragments/1723-zos_query-return-system-subsystem.yml, plugins/module_utils/job.py, plugins/modules/zos_job_query.py, tests/functional/modules/test_zos_job_query_func.py
Enabled the dd scan when fetching a job status, while this is less performant it enables us to fetch both SYSTEM and NODE values from JES output.
We know that this won't be the same final implementation that will go into `dev` branch since we have requested ZOAU to provide these values when fetching the job list instead of us parsing the JES output.
Fixes #1681 
zos_job_query
=> [v1.9.3][zos_job_query] Return system and subsystem values when querying a job.

ac, changelogs/fragments/1744-zos_copy-racf-uacc-updates.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py, tests/helpers/users.py
This addresses #1254 that updates the `zos_copy` code that calls opercmd to check if data sets are in use. When the user does not have SAF UACC for ZOAU SAF Profile 'MVS.MCSOPER.ZOAU' and SAF Class OPERCMDS, an exception is  thrown by ZOAU and the code now catches it and handles it. 
To support this in automation, another story #1757  was opened to create an api that enables test cases to request various types of id's to use in the automated test cases, one such OMVS segment is one that does not have the proper access to run opercmd and causes the exception. 
When using the new `users.py`, please review the comments/pydoc in the api, as there are some limitations in place because pytest-ansible does not support all the Ansible proper options , until that changes, we do have some …
=> Correct zos_copy handling of a zoauresponse during opercmd usage for locked data sets.

changelogs/fragments/1759-system-subsystem-job_query.yml, plugins/module_utils/job.py, plugins/modules/zos_job_query.py, tests/functional/modules/test_zos_job_query_func.py
Enabled the dd scan when fetching a job status, while this is less performant it enables us to fetch both SYSTEM and NODE values from JES output.
We know that this won't be the same final implementation that will go into dev branch since we have requested ZOAU to provide these values when fetching the job list instead of us parsing the JES output.
Same as #1723  but this time for dev branch.
Fixes #1681 
```paste below
```
=> [Bug]Return system and subsystem in zos_job_query

changelogs/fragments/1761-system-subsystem-job_query.yml, plugins/module_utils/job.py, plugins/modules/zos_job_query.py, tests/functional/modules/test_zos_job_query_func.py
Enabled the dd scan when fetching a job status, while this is less performant it enables us to fetch both SYSTEM and NODE values from JES output.
We know that this won't be the same final implementation that will go into dev branch since we have requested ZOAU to provide these values when fetching the job list instead of us parsing the JES output.
Same as https://github.com/ansible-collections/ibm_zos_core/pull/1723 but this time for dev branch.
Fixes https://github.com/ansible-collections/ibm_zos_core/issues/1681
zos_job_query
```paste below
```
=> [v1.12.0][Bug]Return system and subsystem in zos_job_query

changelogs/fragments/1773-fix_absent_inheritance.yml, plugins/modules/zos_unarchive.py
Fix bad inheritance in xmit classes for zos unarchive
```paste below
```
=> [bug][zos_unarchive]Fix_absent_of_inheritance

changelogs/fragments/1775-zos_mvs_raw-size-tests.yml, tests/functional/modules/test_zos_mvs_raw_func.py
Fixes size used for datasets in the test suite.
zos_mvs_raw
Pipeline results:
=> [Bugfix] [zos_mvs_raw] [Tests] Added correct dataset size in zos_mvs_raw test

changelogs/fragments/1774-zos_mvs_raw-verbose-fail.yml, changelogs/fragments/1780-zos_mvs_raw-verbose-fail.yml, plugins/modules/zos_mvs_raw.py, tests/functional/modules/test_zos_mvs_raw_func.py
Looks like mvccmd utility won't return anything in the stderr even if a program executed fails, so we only changed and if statement.
Changing that statement from 'and' to 'or' will in theory, fail any non-zero programs, which is better than having them fail only when verbose=True. Anyways, there is a task in the backlog to add a max_rc option to the module, so we can polish this mechanism there.
While testing this noticed that the module will hide the return code coming from the program if it fail, returning 8 as return code instead, fixed that and had to change some test cases that were expecting a wrong return code.
**NOTE: This was not originally added into the beta release because there was no time to test the fix with latest code. Good thing that we did, because we found and edge …
=> [1.12.0][Bug][zos_mvs_raw] Bugfix/zos mvs raw verbose 1.12

changelogs/fragments/1799-zos_mvs_raw-verbose-fail.yml, plugins/module_utils/zos_mvs_raw.py, plugins/modules/zos_mvs_raw.py, tests/functional/modules/test_zos_mvs_raw_func.py
Fix False positive when RC != 0 and verbosity is false, fix not obfuscate program return codes when failing and stdout replaced by stderr.
This fix was originally planned to be in v1.11.1 just to remove the following lines from the code:
```python
if rc == 0 and verbose:
out = err
```
This issue was reported by the CICS collection, after testing the module I was not able to find a case that returned some output in `stdout` when the command `mvscmd` ran successfully. So why was CICS experiencing issues with this change? That is because they are using `mvscmd.execute` function directly, now, our collection is not intended to be used as a library, but if they are using it is fine, we are not reverting this change to support them, we are reverting this change because it is legitimately a bug …
=> [v1.11.1][Bug][zos_mvs_raw] Multiple fixes

changelogs/fragments/1801-zos_mvs_raw-fail-when-rc-is-0-and-verbose-true.yml, plugins/modules/zos_mvs_raw.py, tests/functional/modules/test_zos_mvs_raw_func.py
With the release v1.9.3 a new bug was introduced, that when a program exits with return code 0 and verbose is True, the module will fail because `stderr` is populated.
Now since mvscmd uses stderr to display verbose messages the module will not use it as a criteria for failure.
Fixes #1793 
zos_mvs_raw
```paste below
```
=> [v1.9.4][Bug][zos_mvs_raw]Fix fail when return code is 0 and verbose is True

changelogs/fragments/1800-zos_mvs_raw-stdout-replaced-by-stderr.yml, plugins/module_utils/zos_mvs_raw.py
**This is the same fix as** #1794
Module would return stderr in stdout when verbosity true and rc = 0
This fix was originally planned to be in v1.11.1 just to remove the following lines from the code:
```python
if rc == 0 and verbose:
out = err
```
This issue was reported by the CICS collection, after testing the module I was not able to find a case that returned some output in `stdout` when the command `mvscmd` ran successfully. So why was CICS experiencing issues with this change? That is because they are using `mvscmd.execute` function directly, now, our collection is not intended to be used as a library, but if they are using it is fine, we are not reverting this change to support them, we are reverting this change because it is legitimately a bug from users perspective, to get …
=> [v1.12.0][Bug][zos_mvs_raw] Remove stdout being replaced by stderr when RC=0 and verbosity is true

changelogs/fragments/1804_enhance_error_message_when_failing_import.yml, plugins/module_utils/import_handler.py
Send to the user the full traceback for import errors, also catch python bad configuration
Fixes #1765 
- Enhance Pull Request
__getattr__ only set the value not the method
Playbook
```
- hosts : zvm
collections :
- ibm.ibm_zos_core
gather_facts: False
vars:
ZOAU: "/zoau/v1.2.5"
#ZOAU: "/zoau/v1.3.3"
PYZ: "/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz"
RC_0_DATA_SET_NAME: "USER.WHAT.EVER.ONE"
DATA_SET_TO_LISTCAT: "USER.WHAT.EVER"
IDCAMS_STDIN: " LISTCAT NTRIES('{{ DATA_SET_TO_LISTCAT | upper }}')"
environment: "{{ environment_vars }}"
tasks:
- name: create some data set
block:
- name: create data set to LISTCAT
zos_data_set:
name: "{{ DATA_SET_TO_LISTCAT }}"
type: seq
state: present
replace: yes
- name: mvs raw with verbose with rc=0
zos_mvs_raw:
verbose: True
program_name: idcams
auth: True …
```
=> [Enhancement][1765]enhance_error_message_when_faiiling_to_import

.github/workflows/ac-ansible-test-sanity.yml, changelogs/fragments/1808-zos_mvs_raw-stderr-not-returned.yml, plugins/modules/zos_mvs_raw.py, tests/functional/modules/test_zos_mvs_raw_func.py
stderr is not being populated in the return values, just always being empty. This PR populates the value and introduces a new test case to validate that it is not empty.
Fixes #1805 
zos_mvs_raw
```paste below
```
=> [Bug][zos_mvs_raw] Return stderr in return values

.github/workflows/ac-ansible-test-sanity.yml, changelogs/fragments/1818-zos_find-vsam-disp-old.yml, plugins/modules/zos_find.py, tests/functional/modules/test_zos_find_func.py
Fixes finding a VSAM when DISP=OLD, note that if age is provided the module won't find the data set that is because detailed vls call fails when data set is DISP=OLD.
So, now we are only using `vls -l` when age is provided, that way we can find the VSAM even when DISP=OLD.
Fixes #643 
zos_find
```paste below
```
=> [zos_find] Find VSAM cluster when DISP=OLD

ac, changelogs/fragments/1827-ac-script-update.yml, scripts/venv.sh
Fixes #1725.
- AC script
- scripts/venv.sh
Doesn't fix the issue per se, since it isn't implementing a new pipeline in Jenkins, but this PR brings the AC script's functionality on par with the options we have currently available in Jenkins. It should make testing locally more flexible and starts us on the path to be ready to migrate to SPS.
It also updates `venv.sh` so the config supports executing on Ansible >=2.17.2 and selecting specific volumes to work with.
=> [Enabler] [AC tool] Add more options when testing with the AC tool

changelogs/fragments/1847-zos_mvs_raw-tmphlq-as-backup-hlq.yml, plugins/modules/zos_mvs_raw.py, tests/functional/modules/test_zos_mvs_raw_func.py
The module was not honoring tmp_hlq as the HLQ for backup data sets, it was a minor issue where we were trying to fetch the value from params as "tmphlq" instead of "tmp_hlq". I also added an assertion in the test cases which is supposed to test this, not sure when that got changed.
Fixes #1803 
zos_mvs_raw
=> [zos_mvs_raw] Honor tmp_hlq value when creating backup data sets

.github/ISSUE_TEMPLATE/bug_issue.yml, .github/ISSUE_TEMPLATE/collaboration_issue.yml, .github/ISSUE_TEMPLATE/doc_issue.yml, .github/ISSUE_TEMPLATE/enabler_issue.yml, .github/ISSUE_TEMPLATE/enhancement_feature.issue.yml, plugins/module_utils/zfsadm.py, plugins/modules/zos_zfs_resize.py, tests/functional/modules/test_zos_zfs_resize_func.py, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.17.txt
First draft on support zfs resizing module
Fixes #1717 
**### module_util/zfsadm**
As the aggregate_name is common for activities using command zfsadm, reason to use in the init function and the module to execute any command, the class is expecting to grow for other modules.
```
def __init__(self, aggregate_name, module):
"""Initialize a class with its zfs dataset and allow modules to be executed.
Parameters
----------
aggregate_name : str
Name of the zfs dataset.
module : object
Ansible object to execute commands.
"""
self.aggregate_name = aggregate_name.upper()
self.module = module 
```
Function grow_shrink
Execute the principal function for the module resize, waiting on the confirmation of operation and the extra instructions.
**### modules/zfs_resize** …
=> [Module][1717]new_module_zfs_resize

changelogs/fragments/1852-zos_script-permissions.yml, plugins/modules/zos_script.py, tests/conftest.py, tests/functional/modules/test_zos_script_func.py, tests/helpers/ztest.py
Fixes #1542.
zos_script
This PR also includes a really small fix to how environment variables are handled when running a test with a managed user.
=> [Bugfix] [zos_script] Fix how remote scripts permissions are handled

changelogs/fragments/1866-fix-sanity-2.18-zos_fetch.yml, plugins/modules/zos_fetch.py
Fixed error message ERROR: plugins/modules/zos_fetch.py:412:37: used-before-assignment: Using variable 'rec_total' before assignment happening in sanity tests with ansible-core 2.18.
zos_fetch
```paste below
```
=> [Sanity] [zos_fetch] Sanity error failing with 2.18

changelogs/fragments/1890-zos_copy-test-suite.yml, tests/functional/modules/test_zos_copy_func.py, tests/helpers/users.py
Fixes an issue with testing a test with zos_copy and testing case "test_copy_dest_lock_test_with_no_opercmd_access_pds_without_force_lock" that bug was introduced in PR #1790 because this test suite was not executed, now with this change I tested with all test suites that are linked to the users.py helper utility. This is not automatically discovered by the dependency finder 
```paste below
```
=> [1.13.0-beta.1][zos_copy] Test case with managed users was failing trying to remove a non-existent RACF group

changelogs/fragments/1865-fix-sanity-2.18-encode.yml, plugins/module_utils/encode.py, tests/helpers/users.py
Fixes sanity 2.18 error message: 
ERROR: plugins/module_utils/encode.py:440:27: used-before-assignment: Using variable 'dest_f' before assignment
module_utils/encode.py
```paste below
```
=> [Sanity] [module_utils/encode] Sanity error failing with 2.18

changelogs/fragments/1891-zos_job_submit-include-execution_time.yml, plugins/module_utils/job.py, plugins/modules/zos_job_output.py, plugins/modules/zos_job_query.py, plugins/modules/zos_job_submit.py, tests/functional/modules/test_zos_job_output_func.py, tests/functional/modules/test_zos_job_query_func.py, tests/functional/modules/test_zos_job_submit_func.py
Including jobs execution_time in the modules results #1637
zos_job_submit, zos_job_query, zos_job_output
zos_job_submit module response 
```
ok: [zos_host] => {
"msg": {
"asid": null,
"changed": true,
"creation_date": null,
"ddnames": {
"byte_count": null,
"content": [],
"ddname": null,
"id": null,
"procstep": null,
"record_count": null,
"stepname": null
},
"dest": "/.ansible/tmp/zos_job_submit_202501221760/test.jcl",
"duration": 4,
"execution_time": "00:00:02",
"failed": false,
"gid": 0,
.....................
```
zos_job_output module response
```
...........
"duration": 0,
"execution_time": "00:00:02",
"job_class": "R",
"job_id": "JOB00112",
"job_name": "SLEEP",
"owner": "OMVSADM",
"priority": 1,
"program_name": "BPXBATCH",
"queue_position": 7,
"ret_code": { …
```
=> Added execution_time param in job response parameters

changelogs/fragments/1917-wrong_behaviour_force_lock_parameter.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
When force_lock option is set to False (Default) use function to validate if the data set is locked, when the dataset name include special characters it fails. Change now escape special characters.
Fixer #1898 
Escape dataset name and add simple quotes for calls on the shell for test suite.
=> [Bugfix][1.12.1][1898][zos_copy]Fix zos_copy failing when force_lock is true and data set name contains a special character

changelogs/fragments/1915-fix-conftest.yml, tests/conftest.py
Looks like PR #1912 inserted some duplicated code into tests/conftest.py rendering the tests unusable. Fixed the issue by removing the duplicated code.
tests/conftest.py
=> Fix Contest after duplicated code was mistakenly inserted

changelogs/fragments/1926-fix-beta-branch.yml, docs/source/release_notes.rst, tests/conftest.py
There were a couple of misses in the release notes that we fixed when publishing the docs, now I'm including these to the staging branch so once we publish this GA these are included.
Also, a piece of code was duplicated in the contest.py file, apparently this happens because the main branch and dev branch are too different and git compares both based on commits and not diffs when doing a pull request. We will probably need to change how we handle the `main` branch and not squash merges into there, but rather let it be a copy of `dev`.
With these changes now the test suite can be executed: 
```shell
(venv-2.18) python3 -m pytest --host-pattern=all --zinventory=/Users/fernandoflores/test_config.yml tests/functional/modules/test_zos_script_func.py -x -vvv -k test_rexx_script_with_args …
```
=> [1.13.0] Post release fixes into staging branch

changelogs/fragments/1925-Deprecation-warning-zos-fetch-and-zos-job-submit.yml, tests/functional/modules/test_zos_fetch_func.py, tests/functional/modules/test_zos_job_submit_func.py
As the existing function was giving the Deprecation warning  in the escape sequence in the two functions. 
test_zos_fetch_func.py
test_zos_job_submit_func.py
```paste below
```
=> [Enabler] [zos_job_submit] [zos_fetch] Fix invalid escape sequence that results in DeprecationWarning 

changelogs/fragments/1924-zos_copy-asa-special-char.yml, plugins/module_utils/copy.py, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py
This fix is the same as https://github.com/ansible-collections/ibm_zos_core/pull/1904 but now forward ported into dev.
Fixes zos_copy failing when copying asa text into a data set with special characters in their name. Fix removes any escaping in both source and dest before issuing either OGET or OPUT commands.
Fixes #1921 
zos_copy 
```paste below
```
=> [Bug][1.13.0] Fix zos_copy failing when copying asa characters into a data set with special chars in their name

changelogs/fragments/1956-zoau-version-support-for-test-cases.yml, tests/functional/modules/test_zos_apf_func.py, tests/functional/modules/test_zos_operator_func.py, tests/helpers/version.py
Test_zos_operator_func.py and test_zos_apf_func.py need the zoau version for a few test cases. 
As the test cases run locally and it does not have access to the zoautil_py module we can not use the zoau_version_checker.py included in the plugins/modue_utils to execute the test cases as well. 
A new helper is defined in the tests names version.py. Similar to the zoau_version_checker.py but it uses the command zoaversion to fetch the version info rather than the zoautil_py module. 
It help in local and pipeline testing. 
- test_zos_apf_func.py
- test_zos_operator_func.py
- tests/helpers/version.py
```paste below
```
=> [zos_operator] Update zos_operator test cases with new way to get zoau version

changelogs/fragments/1954-zos_copy-cr-removal-while-copying-file-to-remote.yml, plugins/modules/zos_copy.py, tests/functional/modules/test_zos_copy_func.py, tests/functional/modules/test_zos_script_func.py
automatic removal of line breaks(CR) while copying files using zos copy #1692
zos_copy, zos_script
-> Implemented logic to remove CR while copying a file to remote directory.
-> Fixed issue related to the carriage return characters were being removed from only first 1KB of a file.
-> Added new test case in zos_script test cases for this use case.
=> [zos_script][zos_copy] Support automatic removal of carriage return characters (CR) when copying files 

changelogs/fragments/1964-zos_data_test-fixing-gdg-replace-issue, plugins/module_utils/data_set.py, tests/functional/modules/test_zos_data_set_func.py
Replacing a GDG is failing with TypeError #1958
zos_data_set
As part of replacing GDG, existing GDG need to be deleted first and after new GDG need to be added. Force removal of existing GDG should be done but instead currently direct removal without force is throwing TypeError. So fixed this issue by passing Force=True when deleting existing GDG as part of replace functionality.
Test results:
Before fixing the issue...
After fixing the issue....
=> [zos_data_set] GDG creation failing when using replace option

changelogs/fragments/1970-update-zos_copy-wildcard.yml, plugins/modules/zos_copy.py
Document copy behavior of 'SOME.TEST.PDS(*)' in zos_copy, as stated we can use wildcards to copy members, but this option allows to copy all members from source without replacing destination PDS.
Fixes #1950 
zos_copy
```paste below
```
=> [Documentation][zos_copy] Document copy behavior of 'SOME.TEST.PDS(*)' as source

changelogs/fragments/2025-Add_documentation_of_false_negatives_and_ensure_proper_testing.yml, plugins/modules/zos_blockinfile.py, tests/functional/modules/test_zos_blockinfile_func.py
Previous we have some false positives cases with backup, to avoid false positives and verify the proper work of the module is required to add the backup validation, fixing #629, but open a new issue been #2024 to work on a specific problem of backups, if the backup required to be same time as the original MVS or could be SEQ with PDS, meanwhile, add to the documentation how avoid false positives.
Verify the type of backup is use and verify the content of the backup.
=> [Enabler][zos_blockinfile]Add_documentation_of_false_negatives_and_ensure_proper_testing

changelogs/fragments/2039-documentation-zos_copy-opercmd.yml, plugins/modules/zos_copy.py
The need of `opercmd` was removed in #1917 but no changes to the docs were performed, so now we are removing it from docs.
Fixes #2036 
zos_copy
=> [Documentation][zos_copy] Remove the need of MVS.MCSOPER.ZOAU profile from the docs

changelogs/fragments/2035-zos_data_set-fixing-gdg-replace-and-empty-gdg-removal-issues.yaml, plugins/module_utils/data_set.py, tests/conftest.py, tests/functional/modules/test_zos_data_set_func.py, tests/functional/modules/test_zos_mount_func.py, tests/functional/modules/test_zos_unarchive_func.py, tests/functional/modules/test_zos_volume_init_func.py, tests/helpers/volumes.py
Fixes #2003 and #2004
zos_data_set
- Fixed issue related to TypeError while replacing an existing GDG.
- Fixed issue which was occurring while deleting an GDG which is not existed.
- Added support of dynamic volumes and allocations for testing zos_volume_init module.
- Decreased required cylinders for initialising volume to 10 cyl in zos_mount testing.
=> [v1.13.1][Bugfixes] [zos_data_set] Fixing GDG replace and empty GDG removal issues

changelogs/fragments/2047-zos_fetch-update-docs.yml, plugins/modules/zos_fetch.py
Updated the documentation in the module about the flat option because it was saying that the default behavior was flat, and in fact the default behavior was creating the whole path for the artifact.
=> [Documentation] Update zos_fetch documentation to be clear about flat value

changelogs/fragments/2055-Zos_apf-shell-commands-to-api.yml, plugins/modules/zos_apf.py
We were previously using the apfadm command to add or remove datasets from the APF list.
Now that the Python API is working and the issue with datasets containing a $ in their names has been resolved, we are reverting to using the API instead of shell commands.   
Test results of sample playbook tested post changes
```paste below
(venv-2.18) ansible-playbook -i inventories/ apf.yml
PLAY [zos_host] ***********************************************************************************************************
TASK [Add library to APF list 1st time] ***********************************************************************************
changed: [zos_host]
TASK [Debug 1st addition] ************************************************************************************************* …
```
=> zos_apf python module port shell commands to python apis

changelogs/fragments/2057-zos_data_set&data_set-Ensure-Dataset-Volume-Validation.yml, plugins/module_utils/data_set.py, plugins/modules/zos_data_set.py, tests/functional/modules/test_zos_data_set_func.py
Enhanced the dataset creation logic to fail explicitly when a dataset already exists on a different volume than requested 
Fixes #1269 
zos_data_set, data_set
```yml
- hosts: zvm
collections:
- ibm.ibm_zos_core
gather_facts: False
#vars:
#ZOAU: "/zoau/v1.3.4"
#PYZ: "/allpython/3.13/usr/lpp/IBM/cyp/v3r13/pyz"
environment: "{{ environment_vars }}"
tasks:
- name: create data set on some volume
zos_data_set:
name: MY.MIN.SIZE.TEST62.DATASET
state: present
volumes:
- "000000"
- name: create data set on a different volume
zos_data_set:
name: MY.MIN.SIZE.TEST62.DATASET
state: present
volumes:
- "222222"
(venv-2.18) ansible-playbook -i inventories/ attempt_data.yml 
PLAY [zvm] *********************************************************************
TASK [create data set on some …
```
=> [Bug] [zos_data_set] Ensure Dataset Volume Validation

changelogs/fragments/2080-zos_lineinfile-fixed-json-parsing.yml, plugins/modules/zos_lineinfile.py, tests/functional/modules/test_zos_lineinfile_func.py
Enhanced JSON parsing logic for zos_lineinfile.
Added fallback cleaning of invalid escape sequences if initial parse fails.
Ensured cmd, changed, and found keys are reliably captured in results.
Prevented task failure on bad JSON when an update still occurs.
Rationale:
Fixes task failures from malformed escape sequences in zoau output.
Improves module robustness and accuracy of result reporting.
#1088 
zos_lineinfile
```yml
SK [Check and insert line in dataset] *******************************************************************************************************************
changed: [zvm]
TASK [Print the result of zos_lineinfile] *****************************************************************************************************************
ok: [zvm] => { …
```
=> [zos_lineinfile]Robust JSON Parsing and Cmd Cleanup 

changelogs/fragments/2079-become-use-zos_fetch.yml, plugins/action/zos_fetch.py
Fixes #1660.
zos_fetch
Updates the SSH options inside `_transfer_remote_content` to use the correct user when `become` and `become_user` are used.
=> [Bugfix] [zos_fetch] Fix permission issue when using become and become_user

changelogs/fragments/2109-copy-fix-tmp-dir.yml, plugins/action/zos_copy.py, plugins/action/zos_job_submit.py, tests/functional/modules/test_zos_copy_func.py
This PR fixes two issues that were closely related, first, the issue of failing when the remote tmp dir is not present was because it is created once an ansiball is executed on the remote node, so, in our action plugins we were doing calls to that remote folder before giving it the chance to get created. That was fixed by returning to use file module in order to create the remote temporary file, not the remote tmp dir folder, but rather the file that is used by both modules: zos_job_submit and zos_copy. This automatically creates the remote temporary dir structure needed for the modules.
it is a port of #2101 
Fix #2106 
zos_copy
zos_job_submit
=> [v1.14.0] Avoid failures when default dir ~/.ansible/tmp/ is not previously created and fix failures when using become in zos_job_submit

changelogs/fragments/2105-zos_unarchive-encoding-support.yml, plugins/modules/zos_unarchive.py, tests/functional/modules/test_zos_unarchive_func.py
Adding the Encoding support in the Unarchive module. 
These changes add the encoding support for MVS and USS files in the unarchive module and Also lists the files that were encoded or failed encoding.
Zos_Unarchive
```paste below
Sample Test Playbook 
---
- hosts: zos_host
collections:
- ibm.ibm_zos_core
gather_facts: false
environment: "{{ environment_vars }}"
vars:
dataset1: "OMVSADM.mvs.test1"
datasetterse1: "OMVSADM.MVS1.TRS"
tasks:
- name: Write test data to input dataset1
zos_copy:
content: "testing  the encoding ? hello ! world dataset1 "
dest: "{{dataset1}}"
force: true
- name: Archive data set into a terse
zos_archive:
src: 
- "{{dataset1}}"
dest: "{{datasetterse1}}"
format:
name: terse
register: terse1
ignore_errors: true
- name: debug text file …
```
=> Encoding support for zos_unarchive module

changelogs/fragments/2136-zos_unarchive_skip_encoding_support.yml, plugins/modules/zos_unarchive.py, tests/functional/modules/test_zos_unarchive_func.py
In the zos_unarhcive module  like the exclude option is there to exclude any dataset or file from the unarchive operation similarly skip encoding is added to the module so as user can skip  the encoding of certain files post unarchiving these files. 
zos_unarchive
```paste below
```
=> Adds option to skip encoding for zos_unarchive module

changelogs/fragments/2137-zos_stat-new-fields.yml, docs/source/modules/zos_stat.rst, plugins/modules/zos_stat.py, tests/functional/modules/test_zos_stat_func.py
Fixes #2113. Fixes #2112.
zos_stat
Adds four new fields to the return JSON of the module:
- isfile
- isdataset
- isaggregate
- isgdg
Names could be changed if requested. Additionally, the module now doesn't fail when the resource is not found on the system, instead returning the following:
```json
{
"changed": false,
"stat": {
"name": "name",
"resource_type": "resource_type",
"exists": false
}
}
```
The return values could be expanded to include all 4 new fields in this case too.
=> [Enhancement] [zos_stat] Extra return values for automation

changelogs/fragments/2109-copy-fix-tmp-dir.yml, changelogs/fragments/2115-copy-fix-tmp-dir.yml, plugins/action/zos_copy.py, plugins/action/zos_job_submit.py, tests/functional/modules/test_zos_copy_func.py
This PR fixes two issues that were closely related, first, the issue of failing when the remote tmp dir is not present was because it is created once an ansiball is executed on the remote node, so, in our action plugins we were doing calls to that remote folder before giving it the chance to get created. That was fixed by returning to use file module in order to create the remote temporary file, not the remote tmp dir folder, but rather the file that is used by both modules: zos_job_submit and zos_copy. This automatically creates the remote temporary dir structure needed for the modules.
it is a port of https://github.com/ansible-collections/ibm_zos_core/pull/2101
Fix #2107
zos_copy
zos_job_submit
=> Avoid failures when default dir ~/.ansible/tmp/ is not previously created and fix failures when using become in zos_job_submit

.github/ISSUE_TEMPLATE/bug_issue.yml, .github/ISSUE_TEMPLATE/collaboration_issue.yml, .github/ISSUE_TEMPLATE/doc_issue.yml, changelogs/fragments/2196-fix-copy-permission-issues.yml, plugins/action/zos_copy.py, plugins/action/zos_job_submit.py
This PR practically reverts the change done in #2109 [v1.14.0] Avoid failures when default dir ~/.ansible/tmp/ is not previously created and fix failures when using become in zos_job_submit, but keeps the functionality of working correctly when the `become` keyword is used in `zos_job_submit` and will not fail if ~/.ansible/tmp/ is not created. But reverts the use of `file` ansible module, which created problems when using the `become` keyword since files were created by BPXROOT in the non-root user folder.
Also, corrects the incorrect use of mode = `666` which left the files unusable, fixes #2196.
zos_copy
zos_job_submit
=> [1.14.1][zos_copy] Fix permission denied when transferring file to managed node with non-root user

changelogs/fragments/2230_zos_operator_interface_update.yml, plugins/modules/zos_operator.py, tests/functional/modules/test_zos_operator_func.py, tests/functional/modules/test_zos_replace_func.py
Update module zos_operator interface.
Fixes #2158 
Add unit_time option for select centiseconds and seconds also as return value.
=> [Enabler][zos_operator] Update module interface

changelogs/fragments/2236-space-type-default-zos_backup_restore.yml, plugins/modules/zos_backup_restore.py, tests/functional/modules/test_zos_backup_restore.py
Comments a test case that currently is a ZOAU bug, this to enable team members to continue testing without regressions. Also, sets 'm' as space type default as stated in the documentation page
```paste below
```
=> [Bug] [zos_backup_restore] Comment test case and fixes byte removal by ZOAU

changelogs/fragments/2240-fix2.18-zos_zfs_resize.yml, tests/functional/modules/test_zos_zfs_resize_func.py
Changed the logic of instead of getting the full dump from dcat command we instead get it piped through `wc` so that we know if the data set is empty or not.
Fix #2227
zos_zfs_resize
=> [Enabler][zos_zfs_resize] Updated zos_zfs_resize test that failed on ansible 2.18

changelogs/fragments/2251-zos_job_output-input-sysin_dd-rename.yml, plugins/modules/zos_job_output.py, tests/functional/modules/test_zos_job_output_func.py
Option input was added to retrieve the sysin dd content,  now its changed to sysin_dd as a boolean, behavior is same its just the option name that is refactored.
zos_job_output
```paste below
```
=> Rename option name input to sysin_dd for job_output

changelogs/fragments/2259-reduce-test-dep-zos_data_set.yml, plugins/action/zos_script.py, plugins/action/zos_unarchive.py, tests/functional/modules/test_zos_backup_restore.py, tests/functional/modules/test_zos_blockinfile_func.py, tests/functional/modules/test_zos_job_output_func.py, tests/functional/modules/test_zos_job_query_func.py, tests/functional/modules/test_zos_lineinfile_func.py, tests/functional/modules/test_zos_mount_func.py, tests/functional/modules/test_zos_volume_init_func.py
Removes calls to zos_data_set in various test suite files, that results in fewer test files being tested when making changes to zos_data_set code coming from :
```
(AC2.18PY3.13) fernandoflores@192 tests % ./dependencyfinder.py -p .. -b dev -s functional/modules/test_module_security.py  -m
../tests/functional/modules/test_zos_apf_func.py ../tests/functional/modules/test_zos_volume_init_func.py ../tests/functional/modules/test_zos_mount_func.py ../tests/functional/modules/test_zos_find_func.py ../tests/functional/modules/test_zos_blockinfile_func.py ../tests/functional/modules/test_zos_backup_restore.py ../tests/functional/modules/test_zos_job_submit_func.py ../tests/functional/modules/test_zos_job_query_func.py ../tests/functional/modules/test_zos_zfs_resize_func.py …
```
=> [Enabler] Remove dependencies from tests when testing zos_data_set

changelogs/fragments/2255-data_set-Enhance-error-message.yml, plugins/module_utils/data_set.py
Override Zoau Error response with more descriptive error messages
Fix #1985 
data_set
```yml
- name: Delete GDG base
zos_data_set:
name: "NAZARE.WDEPLOY.ANSIBLE.TEST"
type: gdg
state: absent
force: true
register: dataset_creation
- name: Print dataset creation output
debug:
msg:
- "Dataset creation output: {{dataset_creation }}"
```
```yml
The full traceback is:
File "/tmp/ansible_zos_data_set_payload_ecjuam8_/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py", line 1965, in run_module
current_changed = perform_data_set_operations(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/ansible_zos_data_set_payload_ecjuam8_/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py", line …
```
=> [Enhancement][data_set]Enhance error messages when not able to delete GDGs

changelogs/fragments/2265-stabilize-zos_archive-tests.yml, tests/functional/modules/test_zos_archive_func.py, tests/functional/modules/test_zos_encode_func.py
Addresses part of the issue of #2258, in that PR I removed a zos_lineinfile code that left some files behind, now after finding some other tests in zos_encode that left files behind I'm making the following changes:
1.- Modify the `zos_encode` test cases so that no temporary files are being left behind.
2.- Modify the way `dls` is executed in `zos_archive` tests, so that if in the future there is a temporary file like `ANSIBLE.TEST.ABC` as a uss file using `dls ANSIBLE.*` won;t get resolved to `dls ANSIBLE.TEST.ABC` but now we are using single quotes around the wildcard (`dls 'ANSIBLE.*'`) so shell doesn't resolve `ANSIBLE.*` making the tests fail.
zos_encode
zos_archive
=> [Enabler] Stabilize zos_archive tests

.gitignore, ansible.cfg
ansible.cfg was added to the ac tool repo when it was separated. we need to have ansible.cfg in ibm_zos_core dir.
when a new version of the repository is pulled it will not have the ansible.cfg.
```paste below
```
=> adding ansible.cfg back to resolve action plugin issue

changelogs/fragments/2347-zos_mount_persistant_delete_all_content.yaml, plugins/modules/zos_mount.py, tests/functional/modules/test_zos_mount_func.py
Code before delete the dataset and write the content that do not match specifications expected by the module, now if there is no match the content will remain on the text and also avoid to delete the dataset, only delete content in case of a match.
Fixes #2285 
Use zos_replace logic to the deletion of content of the dataset
=> [Bugfix][2285]zos_mount_persistant_delete_all_content
